<?php

namespace Adlino\IranGeo\Database\Seeds;

use Adlino\IranGeo\Models\County;
use Illuminate\Database\Seeder;

class CountiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        County::insert([
            [
                'id' => 1,
                'province_id' => 1,
                'name' => 'آذرشهر',
                'en_name' => 'Azarshahr',
                'latitude' => '37.755143',
                'longitude' => '45.868963',
            ],
            [
                'id' => 2,
                'province_id' => 1,
                'name' => 'اسکو',
                'en_name' => 'Osku',
                'latitude' => '37.947687',
                'longitude' => '45.79345',
            ],
            [
                'id' => 3,
                'province_id' => 1,
                'name' => 'اهر',
                'en_name' => 'Ahar',
                'latitude' => '38.489431',
                'longitude' => '47.068358',
            ],
            [
                'id' => 4,
                'province_id' => 1,
                'name' => 'بستان آباد',
                'en_name' => 'Bostan Abad',
                'latitude' => '37.843106',
                'longitude' => '46.83035',
            ],
            [
                'id' => 5,
                'province_id' => 1,
                'name' => 'بناب',
                'en_name' => 'Bonab',
                'latitude' => '37.344596',
                'longitude' => '46.05648',
            ],
            [
                'id' => 6,
                'province_id' => 1,
                'name' => 'تبریز',
                'en_name' => 'Tabriz',
                'latitude' => '38.096239',
                'longitude' => '46.273801',
            ],
            [
                'id' => 7,
                'province_id' => 1,
                'name' => 'جلفا',
                'en_name' => 'Jolfa',
                'latitude' => '38.930737',
                'longitude' => '45.628868',
            ],
            [
                'id' => 8,
                'province_id' => 1,
                'name' => 'چاراویماق',
                'en_name' => 'Charoimagh',
                'latitude' => '36.904145',
                'longitude' => '47.091572',
            ],
            [
                'id' => 9,
                'province_id' => 1,
                'name' => 'خداآفرین',
                'en_name' => 'Khoda Afarin',
                'latitude' => '39.137506',
                'longitude' => '46.961128',
            ],
            [
                'id' => 10,
                'province_id' => 1,
                'name' => 'سراب',
                'en_name' => 'Sarab',
                'latitude' => '37.939977',
                'longitude' => '47.5154373',
            ],
            [
                'id' => 11,
                'province_id' => 1,
                'name' => 'شبستر',
                'en_name' => 'Shabestar',
                'latitude' => '38.1827399',
                'longitude' => '45.6819246',
            ],
            [
                'id' => 12,
                'province_id' => 1,
                'name' => 'عجب شیر',
                'en_name' => 'Ajabshir',
                'latitude' => '37.4825847',
                'longitude' => '45.8735846',
            ],
            [
                'id' => 13,
                'province_id' => 1,
                'name' => 'کلیبر',
                'en_name' => 'Kaleybar',
                'latitude' => '38.8667258',
                'longitude' => '47.0245312',
            ],
            [
                'id' => 14,
                'province_id' => 1,
                'name' => 'مراغه',
                'en_name' => 'Maragheh',
                'latitude' => '37.3808819',
                'longitude' => '46.1906857',
            ],
            [
                'id' => 15,
                'province_id' => 1,
                'name' => 'مرند',
                'en_name' => 'Marand',
                'latitude' => '38.4238783',
                'longitude' => '45.7330793',
            ],
            [
                'id' => 16,
                'province_id' => 1,
                'name' => 'ملکان',
                'en_name' => 'Malekan',
                'latitude' => '37.1464475',
                'longitude' => '46.0862515',
            ],
            [
                'id' => 17,
                'province_id' => 1,
                'name' => 'میانه',
                'en_name' => 'Mianeh',
                'latitude' => '37.4272862',
                'longitude' => '47.6911778',
            ],
            [
                'id' => 18,
                'province_id' => 1,
                'name' => 'ورزقان',
                'en_name' => 'Varzeqān',
                'latitude' => '38.5813659',
                'longitude' => '46.170008',
            ],
            [
                'id' => 19,
                'province_id' => 1,
                'name' => 'هریس',
                'en_name' => 'Heris',
                'latitude' => '38.2495209',
                'longitude' => '47.1078729',
            ],
            [
                'id' => 20,
                'province_id' => 1,
                'name' => 'هشترود',
                'en_name' => 'Hashtrood',
                'latitude' => '37.4775029',
                'longitude' => '47.0369873',
            ],
            [
                'id' => 21,
                'province_id' => 2,
                'name' => 'ارومیه',
                'en_name' => 'Urmia',
                'latitude' => '37.5520103',
                'longitude' => '44.98663',
            ],
            [
                'id' => 22,
                'province_id' => 2,
                'name' => 'اشنویه',
                'en_name' => 'Oshnavieh',
                'latitude' => '37.035787',
                'longitude' => '45.0818394',
            ],
            [
                'id' => 23,
                'province_id' => 2,
                'name' => 'بوکان',
                'en_name' => 'Bukan',
                'latitude' => '36.5215492',
                'longitude' => '46.1653226',
            ],
            [
                'id' => 24,
                'province_id' => 2,
                'name' => 'پلدشت',
                'en_name' => 'Poldasht',
                'latitude' => '39.3484019',
                'longitude' => '45.0583434',
            ],
            [
                'id' => 25,
                'province_id' => 2,
                'name' => 'پیرانشهر',
                'en_name' => 'Piranshahr',
                'latitude' => '36.6964116',
                'longitude' => '45.1285527',
            ],
            [
                'id' => 26,
                'province_id' => 2,
                'name' => 'تکاب',
                'en_name' => 'Takab',
                'latitude' => '36.4008096',
                'longitude' => '47.0787973',
            ],
            [
                'id' => 27,
                'province_id' => 2,
                'name' => 'چالدران',
                'en_name' => 'Chaldoran',
                'latitude' => '39.064678',
                'longitude' => '44.3694447',
            ],
            [
                'id' => 28,
                'province_id' => 2,
                'name' => 'چایپاره',
                'en_name' => 'Chaypareh',
                'latitude' => '38.8901783',
                'longitude' => '45.0081108',
            ],
            [
                'id' => 29,
                'province_id' => 2,
                'name' => 'خوی',
                'en_name' => 'Khoy',
                'latitude' => '38.5484627',
                'longitude' => '44.9341248',
            ],
            [
                'id' => 30,
                'province_id' => 2,
                'name' => 'سردشت',
                'en_name' => 'Sardasht',
                'latitude' => '36.160795',
                'longitude' => '45.4580782',
            ],
            [
                'id' => 31,
                'province_id' => 2,
                'name' => 'سلماس',
                'en_name' => 'Salmas',
                'latitude' => '38.2015592',
                'longitude' => '44.7492455',
            ],
            [
                'id' => 32,
                'province_id' => 2,
                'name' => 'شاهین دژ',
                'en_name' => 'Shahin Dej',
                'latitude' => '36.6775538',
                'longitude' => '46.5505312',
            ],
            [
                'id' => 33,
                'province_id' => 2,
                'name' => 'شوط',
                'en_name' => 'Showt',
                'latitude' => '39.2209468',
                'longitude' => '44.7491597',
            ],
            [
                'id' => 34,
                'province_id' => 2,
                'name' => 'ماکو',
                'en_name' => 'Maku',
                'latitude' => '39.2878546',
                'longitude' => '44.4643301',
            ],
            [
                'id' => 35,
                'province_id' => 2,
                'name' => 'مهاباد',
                'en_name' => 'Mahabad',
                'latitude' => '36.7660413',
                'longitude' => '45.6948438',
            ],
            [
                'id' => 36,
                'province_id' => 2,
                'name' => 'میاندوآب',
                'en_name' => 'Miandoab',
                'latitude' => '36.9662047',
                'longitude' => '46.0710807',
            ],
            [
                'id' => 37,
                'province_id' => 2,
                'name' => 'نقده',
                'en_name' => 'Naqadeh',
                'latitude' => '36.9576384',
                'longitude' => '45.3706598',
            ],
            [
                'id' => 38,
                'province_id' => 3,
                'name' => 'اردبیل',
                'en_name' => 'Ardabil',
                'latitude' => '38.2668309',
                'longitude' => '48.2709933',
            ],
            [
                'id' => 39,
                'province_id' => 3,
                'name' => 'بیله سوار',
                'en_name' => 'Bilesavar',
                'latitude' => '39.3207967',
                'longitude' => '47.6593426',
            ],
            [
                'id' => 40,
                'province_id' => 3,
                'name' => 'پارس آباد',
                'en_name' => 'Parsabad',
                'latitude' => '39.6280219',
                'longitude' => '47.8665727',
            ],
            [
                'id' => 41,
                'province_id' => 3,
                'name' => 'خلخال',
                'en_name' => 'Khalkhal',
                'latitude' => '37.622101',
                'longitude' => '48.50142',
            ],
            [
                'id' => 42,
                'province_id' => 3,
                'name' => 'سرعین',
                'en_name' => 'Sarein',
                'latitude' => '38.1464347',
                'longitude' => '48.0571602',
            ],
            [
                'id' => 43,
                'province_id' => 3,
                'name' => 'کوثر',
                'en_name' => 'Kosar',
                'latitude' => '38.2047581',
                'longitude' => '48.2656235',
            ],
            [
                'id' => 44,
                'province_id' => 3,
                'name' => 'گرمی',
                'en_name' => 'Germi',
                'latitude' => '38.9988011',
                'longitude' => '47.6342799',
            ],
            [
                'id' => 45,
                'province_id' => 3,
                'name' => 'مشگین شهر',
                'en_name' => 'Meshgin Shahr',
                'latitude' => '38.3863287',
                'longitude' => '47.6383489',
            ],
            [
                'id' => 46,
                'province_id' => 3,
                'name' => 'نمین',
                'en_name' => 'Namin',
                'latitude' => '38.4235193',
                'longitude' => '48.4715939',
            ],
            [
                'id' => 47,
                'province_id' => 3,
                'name' => 'نیر',
                'en_name' => 'Nir',
                'latitude' => '38.0334045',
                'longitude' => '47.9977225',
            ],
            [
                'id' => 48,
                'province_id' => 4,
                'name' => 'آران وبیدگل',
                'en_name' => 'Aran va Bidgol',
                'latitude' => '34.0593038',
                'longitude' => '51.4604758',
            ],
            [
                'id' => 49,
                'province_id' => 4,
                'name' => 'اردستان',
                'en_name' => 'Ardestan',
                'latitude' => '33.3807173',
                'longitude' => '52.3430723',
            ],
            [
                'id' => 50,
                'province_id' => 4,
                'name' => 'اصفهان',
                'en_name' => 'Isfahan',
                'latitude' => '32.6625001',
                'longitude' => '51.54694',
            ],
            [
                'id' => 51,
                'province_id' => 4,
                'name' => 'برخوار',
                'en_name' => 'Borkhar',
                'latitude' => '32.8373467',
                'longitude' => '51.6559528',
            ],
            [
                'id' => 52,
                'province_id' => 4,
                'name' => 'بوئین و میاندشت',
                'en_name' => 'Buin va Miandasht',
                'latitude' => '33.0744949',
                'longitude' => '50.1323102',
            ],
            [
                'id' => 53,
                'province_id' => 4,
                'name' => 'تیران و کرون',
                'en_name' => 'Tiran and Karvan',
                'latitude' => '32.8022953',
                'longitude' => '50.8273139',
            ],
            [
                'id' => 54,
                'province_id' => 4,
                'name' => 'چادگان',
                'en_name' => 'Chadegan',
                'latitude' => '32.7807973',
                'longitude' => '50.5471919',
            ],
            [
                'id' => 55,
                'province_id' => 4,
                'name' => 'خمینی شهر',
                'en_name' => 'Khomeyni Shahr',
                'latitude' => '32.6832934',
                'longitude' => '51.4863961',
            ],
            [
                'id' => 56,
                'province_id' => 4,
                'name' => 'خوانسار',
                'en_name' => 'Khansar',
                'latitude' => '33.2674819',
                'longitude' => '50.2487157',
            ],
            [
                'id' => 57,
                'province_id' => 4,
                'name' => 'خور و بیابانک',
                'en_name' => 'Khour va Biabanak',
                'latitude' => '33.6678471',
                'longitude' => '54.1555657',
            ],
            [
                'id' => 58,
                'province_id' => 4,
                'name' => 'دهاقان',
                'en_name' => 'Dehaghan',
                'latitude' => '31.937249',
                'longitude' => '51.6452264',
            ],
            [
                'id' => 59,
                'province_id' => 4,
                'name' => 'سمیرم',
                'en_name' => 'Semirom',
                'latitude' => '31.3979233',
                'longitude' => '51.5444177',
            ],
            [
                'id' => 60,
                'province_id' => 4,
                'name' => 'شاهین شهر و میمه',
                'en_name' => 'Shahinshahr va Meymeh',
                'latitude' => '33.2790548',
                'longitude' => '50.8342176',
            ],
            [
                'id' => 61,
                'province_id' => 4,
                'name' => 'شهرضا',
                'en_name' => 'Shahreza',
                'latitude' => '31.9996877',
                'longitude' => '51.8287747',
            ],
            [
                'id' => 62,
                'province_id' => 4,
                'name' => 'فریدن',
                'en_name' => 'Fereidan',
                'latitude' => '33.0410537',
                'longitude' => '50.2275077',
            ],
            [
                'id' => 63,
                'province_id' => 4,
                'name' => 'فریدون شهر',
                'en_name' => 'Fereydun Shahr',
                'latitude' => '32.937186',
                'longitude' => '50.1202939',
            ],
            [
                'id' => 64,
                'province_id' => 4,
                'name' => 'فلاورجان',
                'en_name' => 'Falavarjan',
                'latitude' => '32.5165967',
                'longitude' => '51.3821021',
            ],
            [
                'id' => 65,
                'province_id' => 4,
                'name' => 'کاشان',
                'en_name' => 'Kashan',
                'latitude' => '33.981549',
                'longitude' => '51.3427137',
            ],
            [
                'id' => 66,
                'province_id' => 4,
                'name' => 'گلپایگان',
                'en_name' => 'Golpayegan',
                'latitude' => '33.4572497',
                'longitude' => '50.2339015',
            ],
            [
                'id' => 67,
                'province_id' => 4,
                'name' => 'لنجان',
                'en_name' => 'Lenjan',
                'latitude' => '32.4558315',
                'longitude' => '51.1626384',
            ],
            [
                'id' => 68,
                'province_id' => 4,
                'name' => 'مبارکه',
                'en_name' => 'Mobarakeh',
                'latitude' => '32.3495215',
                'longitude' => '51.4788216',
            ],
            [
                'id' => 69,
                'province_id' => 4,
                'name' => 'نایین',
                'en_name' => 'Naein',
                'latitude' => '32.8614894',
                'longitude' => '53.074436',
            ],
            [
                'id' => 70,
                'province_id' => 4,
                'name' => 'نجف آباد',
                'en_name' => 'Najafabad',
                'latitude' => '32.6441659',
                'longitude' => '51.3149064',
            ],
            [
                'id' => 71,
                'province_id' => 4,
                'name' => 'نطنز',
                'en_name' => 'Natanz',
                'latitude' => '33.5092644',
                'longitude' => '51.8939208',
            ],
            [
                'id' => 98,
                'province_id' => 8,
                'name' => 'اسلامشهر',
                'en_name' => 'Eslamshahr',
                'latitude' => '35.5828025',
                'longitude' => '51.1918665',
            ],
            [
                'id' => 99,
                'province_id' => 8,
                'name' => 'بهارستان',
                'en_name' => 'Baharestan',
                'latitude' => '35.52198',
                'longitude' => '51.0818745',
            ],
            [
                'id' => 100,
                'province_id' => 8,
                'name' => 'پاکدشت',
                'en_name' => 'Pakdasht',
                'latitude' => '35.4452602',
                'longitude' => '51.6195968',
            ],
            [
                'id' => 101,
                'province_id' => 8,
                'name' => 'پردیس',
                'en_name' => 'Pardis',
                'latitude' => '35.7576389',
                'longitude' => '51.7701559',
            ],
            [
                'id' => 102,
                'province_id' => 8,
                'name' => 'پیشوا',
                'en_name' => 'Pishva',
                'latitude' => '35.3072756',
                'longitude' => '51.7129897',
            ],
            [
                'id' => 103,
                'province_id' => 8,
                'name' => 'تهران',
                'en_name' => 'Tehran',
                'latitude' => '35.6970118',
                'longitude' => '51.2097336',
            ],
            [
                'id' => 104,
                'province_id' => 8,
                'name' => 'دماوند',
                'en_name' => 'Damavand',
                'latitude' => '35.7087312',
                'longitude' => '52.0100624',
            ],
            [
                'id' => 105,
                'province_id' => 8,
                'name' => 'رباطکریم',
                'en_name' => 'Robat Karim',
                'latitude' => '35.4753043',
                'longitude' => '51.0473293',
            ],
            [
                'id' => 106,
                'province_id' => 8,
                'name' => 'ری',
                'en_name' => 'Rey',
                'latitude' => '35.57262',
                'longitude' => '51.4408747',
            ],
            [
                'id' => 107,
                'province_id' => 8,
                'name' => 'شمیرانات',
                'en_name' => 'Shemiranat',
                'latitude' => '35.9312422',
                'longitude' => '51.45978',
            ],
            [
                'id' => 108,
                'province_id' => 8,
                'name' => 'شهریار',
                'en_name' => 'Shahriar',
                'latitude' => '35.659251',
                'longitude' => '51.0068091',
            ],
            [
                'id' => 109,
                'province_id' => 8,
                'name' => 'فیروزکوه',
                'en_name' => 'Firuzkuh',
                'latitude' => '35.7570629',
                'longitude' => '52.7556218',
            ],
            [
                'id' => 110,
                'province_id' => 8,
                'name' => 'قدس',
                'en_name' => 'Qods',
                'latitude' => '35.7107571',
                'longitude' => '51.0791081',
            ],
            [
                'id' => 111,
                'province_id' => 8,
                'name' => 'قرچک',
                'en_name' => 'Qarchak',
                'latitude' => '35.437087',
                'longitude' => '51.5580653',
            ],
            [
                'id' => 112,
                'province_id' => 8,
                'name' => 'ملارد',
                'en_name' => 'Malard',
                'latitude' => '35.6794783',
                'longitude' => '50.9456843',
            ],
            [
                'id' => 113,
                'province_id' => 8,
                'name' => 'ورامین',
                'en_name' => 'Varamin',
                'latitude' => '35.3449427',
                'longitude' => '51.6078465',
            ],
            [
                'id' => 114,
                'province_id' => 9,
                'name' => 'اردل',
                'en_name' => 'Ardal',
                'latitude' => '32.0050834',
                'longitude' => '50.6147855',
            ],
            [
                'id' => 115,
                'province_id' => 9,
                'name' => 'بروجن',
                'en_name' => 'Boroujen',
                'latitude' => '31.9727596',
                'longitude' => '51.271562',
            ],
            [
                'id' => 116,
                'province_id' => 9,
                'name' => 'بن',
                'en_name' => 'Ben',
                'latitude' => '32.5417103',
                'longitude' => '50.7277392',
            ],
            [
                'id' => 117,
                'province_id' => 9,
                'name' => 'سامان',
                'en_name' => 'Saman',
                'latitude' => '32.4486415',
                'longitude' => '50.9025978',
            ],
            [
                'id' => 118,
                'province_id' => 9,
                'name' => 'شهرکرد',
                'en_name' => 'Shahrekord',
                'latitude' => '32.3413787',
                'longitude' => '50.8282466',
            ],
            [
                'id' => 119,
                'province_id' => 9,
                'name' => 'فارسان',
                'en_name' => 'Farsan',
                'latitude' => '32.2566863',
                'longitude' => '50.5522154',
            ],
            [
                'id' => 120,
                'province_id' => 9,
                'name' => 'کوهرنگ',
                'en_name' => 'Koohrang',
                'latitude' => '32.4562338',
                'longitude' => '50.1260775',
            ],
            [
                'id' => 121,
                'province_id' => 9,
                'name' => 'کیار',
                'en_name' => 'Kiar',
                'latitude' => '32.0472047',
                'longitude' => '50.8002446',
            ],
            [
                'id' => 122,
                'province_id' => 9,
                'name' => 'لردگان',
                'en_name' => 'Lordegan',
                'latitude' => '31.5186943',
                'longitude' => '50.7837067',
            ],
            [
                'id' => 123,
                'province_id' => 10,
                'name' => 'بشرویه',
                'en_name' => 'Boshrouyeh',
                'latitude' => '33.8637127',
                'longitude' => '57.4053239',
            ],
            [
                'id' => 124,
                'province_id' => 10,
                'name' => 'بیرجند',
                'en_name' => 'Birjand',
                'latitude' => '32.8706749',
                'longitude' => '59.2069095',
            ],
            [
                'id' => 125,
                'province_id' => 10,
                'name' => 'خوسف',
                'en_name' => 'Khusf',
                'latitude' => '32.7847469',
                'longitude' => '58.8716123',
            ],
            [
                'id' => 126,
                'province_id' => 10,
                'name' => 'درمیان',
                'en_name' => 'Darmiyan',
                'latitude' => '32.9424175',
                'longitude' => '59.5307969',
            ],
            [
                'id' => 127,
                'province_id' => 10,
                'name' => 'زیرکوه',
                'en_name' => 'Zirkuh',
                'latitude' => '33.6032707',
                'longitude' => '59.9903727',
            ],
            [
                'id' => 128,
                'province_id' => 10,
                'name' => 'سرایان',
                'en_name' => 'Sarayan',
                'latitude' => '33.392782',
                'longitude' => '57.7613122',
            ],
            [
                'id' => 129,
                'province_id' => 10,
                'name' => 'سربیشه',
                'en_name' => 'Sarbisheh',
                'latitude' => '32.5807544',
                'longitude' => '59.78204',
            ],
            [
                'id' => 130,
                'province_id' => 10,
                'name' => 'طبس',
                'en_name' => 'Tabas',
                'latitude' => '33.6096045',
                'longitude' => '56.9106382',
            ],
            [
                'id' => 131,
                'province_id' => 10,
                'name' => 'فردوس',
                'en_name' => 'Ferdows',
                'latitude' => '34.0194347',
                'longitude' => '58.1366008',
            ],
            [
                'id' => 132,
                'province_id' => 10,
                'name' => 'قاینات',
                'en_name' => 'Ghayenat',
                'latitude' => '33.6017363',
                'longitude' => '58.6100935',
            ],
            [
                'id' => 133,
                'province_id' => 10,
                'name' => 'نهبندان',
                'en_name' => 'Nehbandan',
                'latitude' => '31.4632964',
                'longitude' => '58.6002157',
            ],
            [
                'id' => 134,
                'province_id' => 11,
                'name' => 'باخرز',
                'en_name' => 'Bakharz',
                'latitude' => '34.9934742',
                'longitude' => '60.2970885',
            ],
            [
                'id' => 135,
                'province_id' => 11,
                'name' => 'بجستان',
                'en_name' => 'Bajestan',
                'latitude' => '34.5235913',
                'longitude' => '58.1394761',
            ],
            [
                'id' => 136,
                'province_id' => 11,
                'name' => 'بردسکن',
                'en_name' => 'Bardaskan',
                'latitude' => '35.2600531',
                'longitude' => '57.9570436',
            ],
            [
                'id' => 137,
                'province_id' => 11,
                'name' => 'بینالود',
                'en_name' => 'Binalood',
                'latitude' => '35.9986306',
                'longitude' => '59.3279701',
            ],
            [
                'id' => 138,
                'province_id' => 11,
                'name' => 'تایباد',
                'en_name' => 'Taybad',
                'latitude' => '34.7443593',
                'longitude' => '60.7544803',
            ],
            [
                'id' => 139,
                'province_id' => 11,
                'name' => 'تربت جام',
                'en_name' => 'Torbat-e-Jam',
                'latitude' => '35.2357736',
                'longitude' => '60.59668',
            ],
            [
                'id' => 140,
                'province_id' => 11,
                'name' => 'تربت حیدریه',
                'en_name' => 'Torbat Heydariyeh',
                'latitude' => '35.2642261',
                'longitude' => '59.1476415',
            ],
            [
                'id' => 141,
                'province_id' => 11,
                'name' => 'جغتای',
                'en_name' => 'Joghatay',
                'latitude' => '36.6406666',
                'longitude' => '57.0607136',
            ],
            [
                'id' => 142,
                'province_id' => 11,
                'name' => 'جوین',
                'en_name' => 'Joveyn',
                'latitude' => '36.621398',
                'longitude' => '57.2812159',
            ],
            [
                'id' => 143,
                'province_id' => 11,
                'name' => 'چناران',
                'en_name' => 'Chenaran',
                'latitude' => '36.6412689',
                'longitude' => '59.1034359',
            ],
            [
                'id' => 144,
                'province_id' => 11,
                'name' => 'خلیل آباد',
                'en_name' => 'Khalil Abad',
                'latitude' => '35.2536776',
                'longitude' => '58.2704114',
            ],
            [
                'id' => 145,
                'province_id' => 11,
                'name' => 'خواف',
                'en_name' => 'Khaf',
                'latitude' => '34.5698972',
                'longitude' => '60.0988191',
            ],
            [
                'id' => 146,
                'province_id' => 11,
                'name' => 'خوشاب',
                'en_name' => 'Khoshab',
                'latitude' => '36.7462211',
                'longitude' => '58.1124628',
            ],
            [
                'id' => 147,
                'province_id' => 11,
                'name' => 'داورزن',
                'en_name' => 'Davarzan',
                'latitude' => '36.3534801',
                'longitude' => '56.8629383',
            ],
            [
                'id' => 148,
                'province_id' => 11,
                'name' => 'درگز',
                'en_name' => 'Dargaz',
                'latitude' => '37.44652',
                'longitude' => '59.0902365',
            ],
            [
                'id' => 149,
                'province_id' => 11,
                'name' => 'رشتخوار',
                'en_name' => 'Rashtkhar',
                'latitude' => '34.9746294',
                'longitude' => '59.6144771',
            ],
            [
                'id' => 150,
                'province_id' => 11,
                'name' => 'زاوه',
                'en_name' => 'Zaveh',
                'latitude' => '35.2759295',
                'longitude' => '59.4588017',
            ],
            [
                'id' => 151,
                'province_id' => 11,
                'name' => 'سبزوار',
                'en_name' => 'Sabzevar',
                'latitude' => '36.2396803',
                'longitude' => '57.5738501',
            ],
            [
                'id' => 152,
                'province_id' => 11,
                'name' => 'سرخس',
                'en_name' => 'Sarakhs',
                'latitude' => '36.5396707',
                'longitude' => '61.1398171',
            ],
            [
                'id' => 153,
                'province_id' => 11,
                'name' => 'فریمان',
                'en_name' => 'Farīmān',
                'latitude' => '35.6995609',
                'longitude' => '59.831115',
            ],
            [
                'id' => 154,
                'province_id' => 11,
                'name' => 'فیروزه',
                'en_name' => 'Firouzeh',
                'latitude' => '36.2828876',
                'longitude' => '58.5676859',
            ],
            [
                'id' => 155,
                'province_id' => 11,
                'name' => 'قوچان',
                'en_name' => 'Quchan',
                'latitude' => '37.1097536',
                'longitude' => '58.3936961',
            ],
            [
                'id' => 156,
                'province_id' => 11,
                'name' => 'کاشمر',
                'en_name' => 'Kashmar',
                'latitude' => '35.2540163',
                'longitude' => '58.4286397',
            ],
            [
                'id' => 157,
                'province_id' => 11,
                'name' => 'کلات',
                'en_name' => 'Kalat',
                'latitude' => '36.9970675',
                'longitude' => '59.733846',
            ],
            [
                'id' => 158,
                'province_id' => 11,
                'name' => 'گناباد',
                'en_name' => 'Gonabad',
                'latitude' => '34.3509863',
                'longitude' => '58.6631291',
            ],
            [
                'id' => 159,
                'province_id' => 11,
                'name' => 'مشهد',
                'en_name' => 'Mashhad',
                'latitude' => '36.297817',
                'longitude' => '59.4393725',
            ],
            [
                'id' => 160,
                'province_id' => 11,
                'name' => 'مه ولات',
                'en_name' => 'Mahvelat',
                'latitude' => '34.9877867',
                'longitude' => '58.4239291',
            ],
            [
                'id' => 161,
                'province_id' => 11,
                'name' => 'نیشابور',
                'en_name' => 'Neyshabur',
                'latitude' => '36.2316328',
                'longitude' => '58.7216536',
            ],
            [
                'id' => 261,
                'province_id' => 18,
                'name' => 'آبیک',
                'en_name' => 'Abyek',
                'latitude' => '36.0471512',
                'longitude' => '50.5181835',
            ],
            [
                'id' => 262,
                'province_id' => 18,
                'name' => 'آوج',
                'en_name' => 'Avaj',
                'latitude' => '35.5777358',
                'longitude' => '49.2120016',
            ],
            [
                'id' => 263,
                'province_id' => 18,
                'name' => 'البرز',
                'en_name' => 'Alborz',
                'latitude' => '36.0235385',
                'longitude' => '50.5568554',
            ],
            [
                'id' => 264,
                'province_id' => 18,
                'name' => 'بویین زهرا',
                'en_name' => 'Buin Zahra',
                'latitude' => '35.7655339',
                'longitude' => '50.0423167',
            ],
            [
                'id' => 265,
                'province_id' => 18,
                'name' => 'تاکستان',
                'en_name' => 'Takestan',
                'latitude' => '36.0708383',
                'longitude' => '49.6609063',
            ],
            [
                'id' => 266,
                'province_id' => 18,
                'name' => 'قزوین',
                'en_name' => 'Qazvin',
                'latitude' => '36.2813381',
                'longitude' => '49.9466454',
            ],
            [
                'id' => 267,
                'province_id' => 19,
                'name' => 'قم',
                'en_name' => 'Qom',
                'latitude' => '34.6887845',
                'longitude' => '50.7119792',
            ],
            [
                'id' => 411,
                'province_id' => 30,
                'name' => 'اسدآباد',
                'en_name' => 'Asadabad',
                'latitude' => '34.7812368',
                'longitude' => '48.1020925',
            ],
            [
                'id' => 412,
                'province_id' => 30,
                'name' => 'بهار',
                'en_name' => 'Bahar',
                'latitude' => '34.893957',
                'longitude' => '48.4032291',
            ],
            [
                'id' => 413,
                'province_id' => 30,
                'name' => 'تویسرکان',
                'en_name' => 'Tuyserkan',
                'latitude' => '34.5481925',
                'longitude' => '48.4323851',
            ],
            [
                'id' => 414,
                'province_id' => 30,
                'name' => 'رزن',
                'en_name' => 'Razan',
                'latitude' => '35.3879465',
                'longitude' => '49.0176485',
            ],
            [
                'id' => 415,
                'province_id' => 30,
                'name' => 'فامنین',
                'en_name' => 'Famenin',
                'latitude' => '35.1130435',
                'longitude' => '48.9569448',
            ],
            [
                'id' => 416,
                'province_id' => 30,
                'name' => 'کبودرآهنگ',
                'en_name' => 'Kabudrahang',
                'latitude' => '35.2094297',
                'longitude' => '48.7067913',
            ],
            [
                'id' => 417,
                'province_id' => 30,
                'name' => 'ملایر',
                'en_name' => 'Malayer',
                'latitude' => '34.301496',
                'longitude' => '48.7882226',
            ],
            [
                'id' => 418,
                'province_id' => 30,
                'name' => 'نهاوند',
                'en_name' => 'Nahavand',
                'latitude' => '34.1948978',
                'longitude' => '48.3392422',
            ],
            [
                'id' => 419,
                'province_id' => 30,
                'name' => 'همدان',
                'en_name' => 'Hamedan',
                'latitude' => '34.8124497',
                'longitude' => '48.4400271',
            ],
            [
                'id' => 420,
                'province_id' => 31,
                'name' => 'ابرکوه',
                'en_name' => 'Abarkooh',
                'latitude' => '31.1263544',
                'longitude' => '53.2215924',
            ],
            [
                'id' => 421,
                'province_id' => 31,
                'name' => 'اردکان',
                'en_name' => 'Ardakan',
                'latitude' => '32.3104532',
                'longitude' => '53.9989613',
            ],
            [
                'id' => 422,
                'province_id' => 31,
                'name' => 'اشکذر',
                'en_name' => 'Ashkezar',
                'latitude' => '32.0007766',
                'longitude' => '54.1923592',
            ],
            [
                'id' => 423,
                'province_id' => 31,
                'name' => 'بافق',
                'en_name' => 'Bafgh',
                'latitude' => '31.6125914',
                'longitude' => '55.3802341',
            ],
            [
                'id' => 424,
                'province_id' => 31,
                'name' => 'بهاباد',
                'en_name' => 'Bahabad',
                'latitude' => '31.8702652',
                'longitude' => '56.0046098',
            ],
            [
                'id' => 425,
                'province_id' => 31,
                'name' => 'تفت',
                'en_name' => 'Taft',
                'latitude' => '31.7575311',
                'longitude' => '54.1720695',
            ],
            [
                'id' => 426,
                'province_id' => 31,
                'name' => 'خاتم',
                'en_name' => 'Khatam',
                'latitude' => '31.8729614',
                'longitude' => '54.3914155',
            ],
            [
                'id' => 427,
                'province_id' => 31,
                'name' => 'مهریز',
                'en_name' => 'Mehriz',
                'latitude' => '31.5798485',
                'longitude' => '54.4066942',
            ],
            [
                'id' => 428,
                'province_id' => 31,
                'name' => 'میبد',
                'en_name' => 'Meybod',
                'latitude' => '32.2085722',
                'longitude' => '53.9747118',
            ],
            [
                'id' => 429,
                'province_id' => 31,
                'name' => 'یزد',
                'en_name' => 'Yazd',
                'latitude' => '31.879685',
                'longitude' => '54.2667269',
            ],
        ]);
    }
}
