<?php

namespace Adlino\IranGeo\Database\Seeds;

use Adlino\IranGeo\Models\County;
use Illuminate\Database\Seeder;

class CountiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        County::insert([
            [
                'id' => 1,
                'province_id' => 1,
                'name' => 'آذرشهر',
                'en_name' => 'Azarshahr',
                'latitude' => '37.755143',
                'longitude' => '45.868963',
            ],
            [
                'id' => 2,
                'province_id' => 1,
                'name' => 'اسکو',
                'en_name' => 'Osku',
                'latitude' => '37.947687',
                'longitude' => '45.79345',
            ],
            [
                'id' => 3,
                'province_id' => 1,
                'name' => 'اهر',
                'en_name' => 'Ahar',
                'latitude' => '38.489431',
                'longitude' => '47.068358',
            ],
            [
                'id' => 4,
                'province_id' => 1,
                'name' => 'بستان آباد',
                'en_name' => 'Bostan Abad',
                'latitude' => '37.843106',
                'longitude' => '46.83035',
            ],
            [
                'id' => 5,
                'province_id' => 1,
                'name' => 'بناب',
                'en_name' => 'Bonab',
                'latitude' => '37.344596',
                'longitude' => '46.05648',
            ],
            [
                'id' => 6,
                'province_id' => 1,
                'name' => 'تبریز',
                'en_name' => 'Tabriz',
                'latitude' => '38.096239',
                'longitude' => '46.273801',
            ],
            [
                'id' => 7,
                'province_id' => 1,
                'name' => 'جلفا',
                'en_name' => 'Jolfa',
                'latitude' => '38.930737',
                'longitude' => '45.628868',
            ],
            [
                'id' => 8,
                'province_id' => 1,
                'name' => 'چاراویماق',
                'en_name' => 'Charoimagh',
                'latitude' => '36.904145',
                'longitude' => '47.091572',
            ],
            [
                'id' => 9,
                'province_id' => 1,
                'name' => 'خداآفرین',
                'en_name' => 'Khoda Afarin',
                'latitude' => '39.137506',
                'longitude' => '46.961128',
            ],
            [
                'id' => 10,
                'province_id' => 1,
                'name' => 'سراب',
                'en_name' => 'Sarab',
                'latitude' => '37.939977',
                'longitude' => '47.5154373',
            ],
            [
                'id' => 11,
                'province_id' => 1,
                'name' => 'شبستر',
                'en_name' => 'Shabestar',
                'latitude' => '38.1827399',
                'longitude' => '45.6819246',
            ],
            [
                'id' => 12,
                'province_id' => 1,
                'name' => 'عجب شیر',
                'en_name' => 'Ajabshir',
                'latitude' => '37.4825847',
                'longitude' => '45.8735846',
            ],
            [
                'id' => 13,
                'province_id' => 1,
                'name' => 'کلیبر',
                'en_name' => 'Kaleybar',
                'latitude' => '38.8667258',
                'longitude' => '47.0245312',
            ],
            [
                'id' => 14,
                'province_id' => 1,
                'name' => 'مراغه',
                'en_name' => 'Maragheh',
                'latitude' => '37.3808819',
                'longitude' => '46.1906857',
            ],
            [
                'id' => 15,
                'province_id' => 1,
                'name' => 'مرند',
                'en_name' => 'Marand',
                'latitude' => '38.4238783',
                'longitude' => '45.7330793',
            ],
            [
                'id' => 16,
                'province_id' => 1,
                'name' => 'ملکان',
                'en_name' => 'Malekan',
                'latitude' => '37.1464475',
                'longitude' => '46.0862515',
            ],
            [
                'id' => 17,
                'province_id' => 1,
                'name' => 'میانه',
                'en_name' => 'Mianeh',
                'latitude' => '37.4272862',
                'longitude' => '47.6911778',
            ],
            [
                'id' => 18,
                'province_id' => 1,
                'name' => 'ورزقان',
                'en_name' => 'Varzeqān',
                'latitude' => '38.5813659',
                'longitude' => '46.170008',
            ],
            [
                'id' => 19,
                'province_id' => 1,
                'name' => 'هریس',
                'en_name' => 'Heris',
                'latitude' => '38.2495209',
                'longitude' => '47.1078729',
            ],
            [
                'id' => 20,
                'province_id' => 1,
                'name' => 'هشترود',
                'en_name' => 'Hashtrood',
                'latitude' => '37.4775029',
                'longitude' => '47.0369873',
            ],
            [
                'id' => 21,
                'province_id' => 2,
                'name' => 'ارومیه',
                'en_name' => 'Urmia',
                'latitude' => '37.5520103',
                'longitude' => '44.98663',
            ],
            [
                'id' => 22,
                'province_id' => 2,
                'name' => 'اشنویه',
                'en_name' => 'Oshnavieh',
                'latitude' => '37.035787',
                'longitude' => '45.0818394',
            ],
            [
                'id' => 23,
                'province_id' => 2,
                'name' => 'بوکان',
                'en_name' => 'Bukan',
                'latitude' => '36.5215492',
                'longitude' => '46.1653226',
            ],
            [
                'id' => 24,
                'province_id' => 2,
                'name' => 'پلدشت',
                'en_name' => 'Poldasht',
                'latitude' => '39.3484019',
                'longitude' => '45.0583434',
            ],
            [
                'id' => 25,
                'province_id' => 2,
                'name' => 'پیرانشهر',
                'en_name' => 'Piranshahr',
                'latitude' => '36.6964116',
                'longitude' => '45.1285527',
            ],
            [
                'id' => 26,
                'province_id' => 2,
                'name' => 'تکاب',
                'en_name' => 'Takab',
                'latitude' => '36.4008096',
                'longitude' => '47.0787973',
            ],
            [
                'id' => 27,
                'province_id' => 2,
                'name' => 'چالدران',
                'en_name' => 'Chaldoran',
                'latitude' => '39.064678',
                'longitude' => '44.3694447',
            ],
            [
                'id' => 28,
                'province_id' => 2,
                'name' => 'چایپاره',
                'en_name' => 'Chaypareh',
                'latitude' => '38.8901783',
                'longitude' => '45.0081108',
            ],
            [
                'id' => 29,
                'province_id' => 2,
                'name' => 'خوی',
                'en_name' => 'Khoy',
                'latitude' => '38.5484627',
                'longitude' => '44.9341248',
            ],
            [
                'id' => 30,
                'province_id' => 2,
                'name' => 'سردشت',
                'en_name' => 'Sardasht',
                'latitude' => '36.160795',
                'longitude' => '45.4580782',
            ],
            [
                'id' => 31,
                'province_id' => 2,
                'name' => 'سلماس',
                'en_name' => 'Salmas',
                'latitude' => '38.2015592',
                'longitude' => '44.7492455',
            ],
            [
                'id' => 32,
                'province_id' => 2,
                'name' => 'شاهین دژ',
                'en_name' => 'Shahin Dej',
                'latitude' => '36.6775538',
                'longitude' => '46.5505312',
            ],
            [
                'id' => 33,
                'province_id' => 2,
                'name' => 'شوط',
                'en_name' => 'Showt',
                'latitude' => '39.2209468',
                'longitude' => '44.7491597',
            ],
            [
                'id' => 34,
                'province_id' => 2,
                'name' => 'ماکو',
                'en_name' => 'Maku',
                'latitude' => '39.2878546',
                'longitude' => '44.4643301',
            ],
            [
                'id' => 35,
                'province_id' => 2,
                'name' => 'مهاباد',
                'en_name' => 'Mahabad',
                'latitude' => '36.7660413',
                'longitude' => '45.6948438',
            ],
            [
                'id' => 36,
                'province_id' => 2,
                'name' => 'میاندوآب',
                'en_name' => 'Miandoab',
                'latitude' => '36.9662047',
                'longitude' => '46.0710807',
            ],
            [
                'id' => 37,
                'province_id' => 2,
                'name' => 'نقده',
                'en_name' => 'Naqadeh',
                'latitude' => '36.9576384',
                'longitude' => '45.3706598',
            ],
            [
                'id' => 38,
                'province_id' => 3,
                'name' => 'اردبیل',
                'en_name' => 'Ardabil',
                'latitude' => '38.2668309',
                'longitude' => '48.2709933',
            ],
            [
                'id' => 39,
                'province_id' => 3,
                'name' => 'بیله سوار',
                'en_name' => 'Bilesavar',
                'latitude' => '39.3207967',
                'longitude' => '47.6593426',
            ],
            [
                'id' => 40,
                'province_id' => 3,
                'name' => 'پارس آباد',
                'en_name' => 'Parsabad',
                'latitude' => '39.6280219',
                'longitude' => '47.8665727',
            ],
            [
                'id' => 41,
                'province_id' => 3,
                'name' => 'خلخال',
                'en_name' => 'Khalkhal',
                'latitude' => '37.622101',
                'longitude' => '48.50142',
            ],
            [
                'id' => 42,
                'province_id' => 3,
                'name' => 'سرعین',
                'en_name' => 'Sarein',
                'latitude' => '38.1464347',
                'longitude' => '48.0571602',
            ],
            [
                'id' => 43,
                'province_id' => 3,
                'name' => 'کوثر',
                'en_name' => 'Kosar',
                'latitude' => '38.2047581',
                'longitude' => '48.2656235',
            ],
            [
                'id' => 44,
                'province_id' => 3,
                'name' => 'گرمی',
                'en_name' => 'Germi',
                'latitude' => '38.9988011',
                'longitude' => '47.6342799',
            ],
            [
                'id' => 45,
                'province_id' => 3,
                'name' => 'مشگین شهر',
                'en_name' => 'Meshgin Shahr',
                'latitude' => '38.3863287',
                'longitude' => '47.6383489',
            ],
            [
                'id' => 46,
                'province_id' => 3,
                'name' => 'نمین',
                'en_name' => 'Namin',
                'latitude' => '38.4235193',
                'longitude' => '48.4715939',
            ],
            [
                'id' => 47,
                'province_id' => 3,
                'name' => 'نیر',
                'en_name' => 'Nir',
                'latitude' => '38.0334045',
                'longitude' => '47.9977225',
            ],
            [
                'id' => 48,
                'province_id' => 4,
                'name' => 'آران وبیدگل',
                'en_name' => 'Aran va Bidgol',
                'latitude' => '34.0593038',
                'longitude' => '51.4604758',
            ],
            [
                'id' => 49,
                'province_id' => 4,
                'name' => 'اردستان',
                'en_name' => 'Ardestan',
                'latitude' => '33.3807173',
                'longitude' => '52.3430723',
            ],
            [
                'id' => 50,
                'province_id' => 4,
                'name' => 'اصفهان',
                'en_name' => 'Isfahan',
                'latitude' => '32.6625001',
                'longitude' => '51.54694',
            ],
            [
                'id' => 51,
                'province_id' => 4,
                'name' => 'برخوار',
                'en_name' => 'Borkhar',
                'latitude' => '32.8373467',
                'longitude' => '51.6559528',
            ],
            [
                'id' => 52,
                'province_id' => 4,
                'name' => 'بوئین و میاندشت',
                'en_name' => 'Buin va Miandasht',
                'latitude' => '33.0744949',
                'longitude' => '50.1323102',
            ],
            [
                'id' => 53,
                'province_id' => 4,
                'name' => 'تیران و کرون',
                'en_name' => 'Tiran and Karvan',
                'latitude' => '32.8022953',
                'longitude' => '50.8273139',
            ],
            [
                'id' => 54,
                'province_id' => 4,
                'name' => 'چادگان',
                'en_name' => 'Chadegan',
                'latitude' => '32.7807973',
                'longitude' => '50.5471919',
            ],
            [
                'id' => 55,
                'province_id' => 4,
                'name' => 'خمینی شهر',
                'en_name' => 'Khomeyni Shahr',
                'latitude' => '32.6832934',
                'longitude' => '51.4863961',
            ],
            [
                'id' => 56,
                'province_id' => 4,
                'name' => 'خوانسار',
                'en_name' => 'Khansar',
                'latitude' => '33.2674819',
                'longitude' => '50.2487157',
            ],
            [
                'id' => 57,
                'province_id' => 4,
                'name' => 'خور و بیابانک',
                'en_name' => 'Khour va Biabanak',
                'latitude' => '33.6678471',
                'longitude' => '54.1555657',
            ],
            [
                'id' => 58,
                'province_id' => 4,
                'name' => 'دهاقان',
                'en_name' => 'Dehaghan',
                'latitude' => '31.937249',
                'longitude' => '51.6452264',
            ],
            [
                'id' => 59,
                'province_id' => 4,
                'name' => 'سمیرم',
                'en_name' => 'Semirom',
                'latitude' => '31.3979233',
                'longitude' => '51.5444177',
            ],
            [
                'id' => 60,
                'province_id' => 4,
                'name' => 'شاهین شهر و میمه',
                'en_name' => 'Shahinshahr va Meymeh',
                'latitude' => '33.2790548',
                'longitude' => '50.8342176',
            ],
            [
                'id' => 61,
                'province_id' => 4,
                'name' => 'شهرضا',
                'en_name' => 'Shahreza',
                'latitude' => '31.9996877',
                'longitude' => '51.8287747',
            ],
            [
                'id' => 62,
                'province_id' => 4,
                'name' => 'فریدن',
                'en_name' => 'Fereidan',
                'latitude' => '33.0410537',
                'longitude' => '50.2275077',
            ],
            [
                'id' => 63,
                'province_id' => 4,
                'name' => 'فریدون شهر',
                'en_name' => 'Fereydun Shahr',
                'latitude' => '32.937186',
                'longitude' => '50.1202939',
            ],
            [
                'id' => 64,
                'province_id' => 4,
                'name' => 'فلاورجان',
                'en_name' => 'Falavarjan',
                'latitude' => '32.5165967',
                'longitude' => '51.3821021',
            ],
            [
                'id' => 65,
                'province_id' => 4,
                'name' => 'کاشان',
                'en_name' => 'Kashan',
                'latitude' => '33.981549',
                'longitude' => '51.3427137',
            ],
            [
                'id' => 66,
                'province_id' => 4,
                'name' => 'گلپایگان',
                'en_name' => 'Golpayegan',
                'latitude' => '33.4572497',
                'longitude' => '50.2339015',
            ],
            [
                'id' => 67,
                'province_id' => 4,
                'name' => 'لنجان',
                'en_name' => 'Lenjan',
                'latitude' => '32.4558315',
                'longitude' => '51.1626384',
            ],
            [
                'id' => 68,
                'province_id' => 4,
                'name' => 'مبارکه',
                'en_name' => 'Mobarakeh',
                'latitude' => '32.3495215',
                'longitude' => '51.4788216',
            ],
            [
                'id' => 69,
                'province_id' => 4,
                'name' => 'نایین',
                'en_name' => 'Naein',
                'latitude' => '32.8614894',
                'longitude' => '53.074436',
            ],
            [
                'id' => 70,
                'province_id' => 4,
                'name' => 'نجف آباد',
                'en_name' => 'Najafabad',
                'latitude' => '32.6441659',
                'longitude' => '51.3149064',
            ],
            [
                'id' => 71,
                'province_id' => 4,
                'name' => 'نطنز',
                'en_name' => 'Natanz',
                'latitude' => '33.5092644',
                'longitude' => '51.8939208',
            ],
            [
                'id' => 72,
                'province_id' => 5,
                'name' => 'اشتهارد',
                'en_name' => 'Eshtehard',
                'latitude' => '35.7212627',
                'longitude' => '50.3482495',
            ],
            [
                'id' => 73,
                'province_id' => 5,
                'name' => 'ساوجبلاغ',
                'en_name' => 'Savojbolagh',
                'latitude' => '35.950000',
                'longitude' => '50.666667',
            ],
            [
                'id' => 74,
                'province_id' => 5,
                'name' => 'طالقان',
                'en_name' => 'Taleqan',
                'latitude' => '36.214801',
                'longitude' => '50.5065136',
            ],
            [
                'id' => 75,
                'province_id' => 5,
                'name' => 'فردیس',
                'en_name' => 'Fardis',
                'latitude' => '35.724722',
                'longitude' => '50.988333',
            ],
            [
                'id' => 76,
                'province_id' => 5,
                'name' => 'کرج',
                'en_name' => 'Karaj',
                'latitude' => '35.835556',
                'longitude' => '51.010278',
            ],
            [
                'id' => 77,
                'province_id' => 5,
                'name' => 'نظرآباد',
                'en_name' => 'Nazarabad',
                'latitude' => '35.9677474',
                'longitude' => '50.5694241',
            ],
            [
                'id' => 78,
                'province_id' => 6,
                'name' => 'آبدانان',
                'en_name' => 'Abdanan',
                'latitude' => '32.9935805',
                'longitude' => '47.4037312',
            ],
            [
                'id' => 79,
                'province_id' => 6,
                'name' => 'ایلام',
                'en_name' => 'Ilam',
                'latitude' => '33.636955',
                'longitude' => '46.396498',
            ],
            [
                'id' => 80,
                'province_id' => 6,
                'name' => 'ایوان',
                'en_name' => 'Eyvan',
                'latitude' => '33.8282846',
                'longitude' => '46.290314',
            ],
            [
                'id' => 81,
                'province_id' => 6,
                'name' => 'بدره',
                'en_name' => 'Bedreh',
                'latitude' => '33.3066441',
                'longitude' => '47.0296812',
            ],
            [
                'id' => 82,
                'province_id' => 6,
                'name' => 'چرداول',
                'en_name' => 'Chardavol',
                'latitude' => '33.81291',
                'longitude' => '46.6114729',
            ],
            [
                'id' => 83,
                'province_id' => 6,
                'name' => 'دره شهر',
                'en_name' => 'Darreh Shahr',
                'latitude' => '33.1433327',
                'longitude' => '47.3680686',
            ],
            [
                'id' => 84,
                'province_id' => 6,
                'name' => 'دهلران',
                'en_name' => 'Dehloran',
                'latitude' => '32.6911071',
                'longitude' => '47.2526263',
            ],
            [
                'id' => 85,
                'province_id' => 6,
                'name' => 'سیروان',
                'en_name' => 'Sirvan',
                'latitude' => '33.750000',
                'longitude' => '46.566667',
            ],
            [
                'id' => 86,
                'province_id' => 6,
                'name' => 'ملکشاهی',
                'en_name' => 'Malekshahi',
                'latitude' => '33.383333',
                'longitude' => '46.600000',
            ],
            [
                'id' => 87,
                'province_id' => 6,
                'name' => 'مهران',
                'en_name' => 'Mehran',
                'latitude' => '33.1217092',
                'longitude' => '46.156268',
            ],
            [
                'id' => 88,
                'province_id' => 7,
                'name' => 'بوشهر',
                'en_name' => 'Bushehr',
                'latitude' => '28.9110525',
                'longitude' => '50.8300213',
            ],
            [
                'id' => 89,
                'province_id' => 7,
                'name' => 'تنگستان',
                'en_name' => 'Tangestan',
                'latitude' => '28.984037',
                'longitude' => '50.8314871',
            ],
            [
                'id' => 90,
                'province_id' => 7,
                'name' => 'جم',
                'en_name' => 'Jam',
                'latitude' => '27.8158015',
                'longitude' => '52.3099845',
            ],
            [
                'id' => 91,
                'province_id' => 7,
                'name' => 'دشتستان',
                'en_name' => 'Dashtestan',
                'latitude' => '29.283333',
                'longitude' => '51.250000',
            ],
            [
                'id' => 92,
                'province_id' => 7,
                'name' => 'دشتی',
                'en_name' => 'Dashti',
                'latitude' => '28.483333',
                'longitude' => '51.550000',
            ],
            [
                'id' => 93,
                'province_id' => 7,
                'name' => 'دیر',
                'en_name' => 'Dayyer',
                'latitude' => '27.8429067',
                'longitude' => '51.9183272',
            ],
            [
                'id' => 94,
                'province_id' => 7,
                'name' => 'دیلم',
                'en_name' => 'Deylam',
                'latitude' => '30.0610082',
                'longitude' => '50.1461718',
            ],
            [
                'id' => 95,
                'province_id' => 7,
                'name' => 'عسلویه',
                'en_name' => 'Asaluyeh',
                'latitude' => '27.476083',
                'longitude' => '52.6038909',
            ],
            [
                'id' => 96,
                'province_id' => 7,
                'name' => 'کنگان',
                'en_name' => 'Kangan',
                'latitude' => '27.8329631',
                'longitude' => '52.0370751',
            ],
            [
                'id' => 97,
                'province_id' => 7,
                'name' => 'گناوه',
                'en_name' => 'Ganaveh',
                'latitude' => '29.5839337',
                'longitude' => '50.4762977',
            ],
            [
                'id' => 98,
                'province_id' => 8,
                'name' => 'اسلامشهر',
                'en_name' => 'Eslamshahr',
                'latitude' => '35.5828025',
                'longitude' => '51.1918665',
            ],
            [
                'id' => 99,
                'province_id' => 8,
                'name' => 'بهارستان',
                'en_name' => 'Baharestan',
                'latitude' => '35.52198',
                'longitude' => '51.0818745',
            ],
            [
                'id' => 100,
                'province_id' => 8,
                'name' => 'پاکدشت',
                'en_name' => 'Pakdasht',
                'latitude' => '35.4452602',
                'longitude' => '51.6195968',
            ],
            [
                'id' => 101,
                'province_id' => 8,
                'name' => 'پردیس',
                'en_name' => 'Pardis',
                'latitude' => '35.7576389',
                'longitude' => '51.7701559',
            ],
            [
                'id' => 102,
                'province_id' => 8,
                'name' => 'پیشوا',
                'en_name' => 'Pishva',
                'latitude' => '35.3072756',
                'longitude' => '51.7129897',
            ],
            [
                'id' => 103,
                'province_id' => 8,
                'name' => 'تهران',
                'en_name' => 'Tehran',
                'latitude' => '35.6970118',
                'longitude' => '51.2097336',
            ],
            [
                'id' => 104,
                'province_id' => 8,
                'name' => 'دماوند',
                'en_name' => 'Damavand',
                'latitude' => '35.7087312',
                'longitude' => '52.0100624',
            ],
            [
                'id' => 105,
                'province_id' => 8,
                'name' => 'رباطکریم',
                'en_name' => 'Robat Karim',
                'latitude' => '35.4753043',
                'longitude' => '51.0473293',
            ],
            [
                'id' => 106,
                'province_id' => 8,
                'name' => 'ری',
                'en_name' => 'Rey',
                'latitude' => '35.57262',
                'longitude' => '51.4408747',
            ],
            [
                'id' => 107,
                'province_id' => 8,
                'name' => 'شمیرانات',
                'en_name' => 'Shemiranat',
                'latitude' => '35.9312422',
                'longitude' => '51.45978',
            ],
            [
                'id' => 108,
                'province_id' => 8,
                'name' => 'شهریار',
                'en_name' => 'Shahriar',
                'latitude' => '35.659251',
                'longitude' => '51.0068091',
            ],
            [
                'id' => 109,
                'province_id' => 8,
                'name' => 'فیروزکوه',
                'en_name' => 'Firuzkuh',
                'latitude' => '35.7570629',
                'longitude' => '52.7556218',
            ],
            [
                'id' => 110,
                'province_id' => 8,
                'name' => 'قدس',
                'en_name' => 'Qods',
                'latitude' => '35.7107571',
                'longitude' => '51.0791081',
            ],
            [
                'id' => 111,
                'province_id' => 8,
                'name' => 'قرچک',
                'en_name' => 'Qarchak',
                'latitude' => '35.437087',
                'longitude' => '51.5580653',
            ],
            [
                'id' => 112,
                'province_id' => 8,
                'name' => 'ملارد',
                'en_name' => 'Malard',
                'latitude' => '35.6794783',
                'longitude' => '50.9456843',
            ],
            [
                'id' => 113,
                'province_id' => 8,
                'name' => 'ورامین',
                'en_name' => 'Varamin',
                'latitude' => '35.3449427',
                'longitude' => '51.6078465',
            ],
            [
                'id' => 114,
                'province_id' => 9,
                'name' => 'اردل',
                'en_name' => 'Ardal',
                'latitude' => '32.0050834',
                'longitude' => '50.6147855',
            ],
            [
                'id' => 115,
                'province_id' => 9,
                'name' => 'بروجن',
                'en_name' => 'Boroujen',
                'latitude' => '31.9727596',
                'longitude' => '51.271562',
            ],
            [
                'id' => 116,
                'province_id' => 9,
                'name' => 'بن',
                'en_name' => 'Ben',
                'latitude' => '32.5417103',
                'longitude' => '50.7277392',
            ],
            [
                'id' => 117,
                'province_id' => 9,
                'name' => 'سامان',
                'en_name' => 'Saman',
                'latitude' => '32.4486415',
                'longitude' => '50.9025978',
            ],
            [
                'id' => 118,
                'province_id' => 9,
                'name' => 'شهرکرد',
                'en_name' => 'Shahrekord',
                'latitude' => '32.3413787',
                'longitude' => '50.8282466',
            ],
            [
                'id' => 119,
                'province_id' => 9,
                'name' => 'فارسان',
                'en_name' => 'Farsan',
                'latitude' => '32.2566863',
                'longitude' => '50.5522154',
            ],
            [
                'id' => 120,
                'province_id' => 9,
                'name' => 'کوهرنگ',
                'en_name' => 'Koohrang',
                'latitude' => '32.4562338',
                'longitude' => '50.1260775',
            ],
            [
                'id' => 121,
                'province_id' => 9,
                'name' => 'کیار',
                'en_name' => 'Kiar',
                'latitude' => '32.0472047',
                'longitude' => '50.8002446',
            ],
            [
                'id' => 122,
                'province_id' => 9,
                'name' => 'لردگان',
                'en_name' => 'Lordegan',
                'latitude' => '31.5186943',
                'longitude' => '50.7837067',
            ],
            [
                'id' => 123,
                'province_id' => 10,
                'name' => 'بشرویه',
                'en_name' => 'Boshrouyeh',
                'latitude' => '33.8637127',
                'longitude' => '57.4053239',
            ],
            [
                'id' => 124,
                'province_id' => 10,
                'name' => 'بیرجند',
                'en_name' => 'Birjand',
                'latitude' => '32.8706749',
                'longitude' => '59.2069095',
            ],
            [
                'id' => 125,
                'province_id' => 10,
                'name' => 'خوسف',
                'en_name' => 'Khusf',
                'latitude' => '32.7847469',
                'longitude' => '58.8716123',
            ],
            [
                'id' => 126,
                'province_id' => 10,
                'name' => 'درمیان',
                'en_name' => 'Darmiyan',
                'latitude' => '32.9424175',
                'longitude' => '59.5307969',
            ],
            [
                'id' => 127,
                'province_id' => 10,
                'name' => 'زیرکوه',
                'en_name' => 'Zirkuh',
                'latitude' => '33.6032707',
                'longitude' => '59.9903727',
            ],
            [
                'id' => 128,
                'province_id' => 10,
                'name' => 'سرایان',
                'en_name' => 'Sarayan',
                'latitude' => '33.392782',
                'longitude' => '57.7613122',
            ],
            [
                'id' => 129,
                'province_id' => 10,
                'name' => 'سربیشه',
                'en_name' => 'Sarbisheh',
                'latitude' => '32.5807544',
                'longitude' => '59.78204',
            ],
            [
                'id' => 130,
                'province_id' => 10,
                'name' => 'طبس',
                'en_name' => 'Tabas',
                'latitude' => '33.6096045',
                'longitude' => '56.9106382',
            ],
            [
                'id' => 131,
                'province_id' => 10,
                'name' => 'فردوس',
                'en_name' => 'Ferdows',
                'latitude' => '34.0194347',
                'longitude' => '58.1366008',
            ],
            [
                'id' => 132,
                'province_id' => 10,
                'name' => 'قاینات',
                'en_name' => 'Ghayenat',
                'latitude' => '33.6017363',
                'longitude' => '58.6100935',
            ],
            [
                'id' => 133,
                'province_id' => 10,
                'name' => 'نهبندان',
                'en_name' => 'Nehbandan',
                'latitude' => '31.4632964',
                'longitude' => '58.6002157',
            ],
            [
                'id' => 134,
                'province_id' => 11,
                'name' => 'باخرز',
                'en_name' => 'Bakharz',
                'latitude' => '34.9934742',
                'longitude' => '60.2970885',
            ],
            [
                'id' => 135,
                'province_id' => 11,
                'name' => 'بجستان',
                'en_name' => 'Bajestan',
                'latitude' => '34.5235913',
                'longitude' => '58.1394761',
            ],
            [
                'id' => 136,
                'province_id' => 11,
                'name' => 'بردسکن',
                'en_name' => 'Bardaskan',
                'latitude' => '35.2600531',
                'longitude' => '57.9570436',
            ],
            [
                'id' => 137,
                'province_id' => 11,
                'name' => 'بینالود',
                'en_name' => 'Binalood',
                'latitude' => '35.9986306',
                'longitude' => '59.3279701',
            ],
            [
                'id' => 138,
                'province_id' => 11,
                'name' => 'تایباد',
                'en_name' => 'Taybad',
                'latitude' => '34.7443593',
                'longitude' => '60.7544803',
            ],
            [
                'id' => 139,
                'province_id' => 11,
                'name' => 'تربت جام',
                'en_name' => 'Torbat-e-Jam',
                'latitude' => '35.2357736',
                'longitude' => '60.59668',
            ],
            [
                'id' => 140,
                'province_id' => 11,
                'name' => 'تربت حیدریه',
                'en_name' => 'Torbat Heydariyeh',
                'latitude' => '35.2642261',
                'longitude' => '59.1476415',
            ],
            [
                'id' => 141,
                'province_id' => 11,
                'name' => 'جغتای',
                'en_name' => 'Joghatay',
                'latitude' => '36.6406666',
                'longitude' => '57.0607136',
            ],
            [
                'id' => 142,
                'province_id' => 11,
                'name' => 'جوین',
                'en_name' => 'Joveyn',
                'latitude' => '36.621398',
                'longitude' => '57.2812159',
            ],
            [
                'id' => 143,
                'province_id' => 11,
                'name' => 'چناران',
                'en_name' => 'Chenaran',
                'latitude' => '36.6412689',
                'longitude' => '59.1034359',
            ],
            [
                'id' => 144,
                'province_id' => 11,
                'name' => 'خلیل آباد',
                'en_name' => 'Khalil Abad',
                'latitude' => '35.2536776',
                'longitude' => '58.2704114',
            ],
            [
                'id' => 145,
                'province_id' => 11,
                'name' => 'خواف',
                'en_name' => 'Khaf',
                'latitude' => '34.5698972',
                'longitude' => '60.0988191',
            ],
            [
                'id' => 146,
                'province_id' => 11,
                'name' => 'خوشاب',
                'en_name' => 'Khoshab',
                'latitude' => '36.7462211',
                'longitude' => '58.1124628',
            ],
            [
                'id' => 147,
                'province_id' => 11,
                'name' => 'داورزن',
                'en_name' => 'Davarzan',
                'latitude' => '36.3534801',
                'longitude' => '56.8629383',
            ],
            [
                'id' => 148,
                'province_id' => 11,
                'name' => 'درگز',
                'en_name' => 'Dargaz',
                'latitude' => '37.44652',
                'longitude' => '59.0902365',
            ],
            [
                'id' => 149,
                'province_id' => 11,
                'name' => 'رشتخوار',
                'en_name' => 'Rashtkhar',
                'latitude' => '34.9746294',
                'longitude' => '59.6144771',
            ],
            [
                'id' => 150,
                'province_id' => 11,
                'name' => 'زاوه',
                'en_name' => 'Zaveh',
                'latitude' => '35.2759295',
                'longitude' => '59.4588017',
            ],
            [
                'id' => 151,
                'province_id' => 11,
                'name' => 'سبزوار',
                'en_name' => 'Sabzevar',
                'latitude' => '36.2396803',
                'longitude' => '57.5738501',
            ],
            [
                'id' => 152,
                'province_id' => 11,
                'name' => 'سرخس',
                'en_name' => 'Sarakhs',
                'latitude' => '36.5396707',
                'longitude' => '61.1398171',
            ],
            [
                'id' => 153,
                'province_id' => 11,
                'name' => 'فریمان',
                'en_name' => 'Farīmān',
                'latitude' => '35.6995609',
                'longitude' => '59.831115',
            ],
            [
                'id' => 154,
                'province_id' => 11,
                'name' => 'فیروزه',
                'en_name' => 'Firouzeh',
                'latitude' => '36.2828876',
                'longitude' => '58.5676859',
            ],
            [
                'id' => 155,
                'province_id' => 11,
                'name' => 'قوچان',
                'en_name' => 'Quchan',
                'latitude' => '37.1097536',
                'longitude' => '58.3936961',
            ],
            [
                'id' => 156,
                'province_id' => 11,
                'name' => 'کاشمر',
                'en_name' => 'Kashmar',
                'latitude' => '35.2540163',
                'longitude' => '58.4286397',
            ],
            [
                'id' => 157,
                'province_id' => 11,
                'name' => 'کلات',
                'en_name' => 'Kalat',
                'latitude' => '36.9970675',
                'longitude' => '59.733846',
            ],
            [
                'id' => 158,
                'province_id' => 11,
                'name' => 'گناباد',
                'en_name' => 'Gonabad',
                'latitude' => '34.3509863',
                'longitude' => '58.6631291',
            ],
            [
                'id' => 159,
                'province_id' => 11,
                'name' => 'مشهد',
                'en_name' => 'Mashhad',
                'latitude' => '36.297817',
                'longitude' => '59.4393725',
            ],
            [
                'id' => 160,
                'province_id' => 11,
                'name' => 'مه ولات',
                'en_name' => 'Mahvelat',
                'latitude' => '34.9877867',
                'longitude' => '58.4239291',
            ],
            [
                'id' => 161,
                'province_id' => 11,
                'name' => 'نیشابور',
                'en_name' => 'Neyshabur',
                'latitude' => '36.2316328',
                'longitude' => '58.7216536',
            ],
            [
                'id' => 162,
                'province_id' => 12,
                'name' => 'اسفراین',
                'en_name' => 'Esfarāyen',
                'latitude' => '37.0633842',
                'longitude' => '57.4730009',
            ],
            [
                'id' => 163,
                'province_id' => 12,
                'name' => 'بجنورد',
                'en_name' => 'Bojnurd',
                'latitude' => '37.4842089',
                'longitude' => '57.2554615',
            ],
            [
                'id' => 164,
                'province_id' => 12,
                'name' => 'جاجرم',
                'en_name' => 'Jajarm',
                'latitude' => '36.9616101',
                'longitude' => '56.3304443',
            ],
            [
                'id' => 165,
                'province_id' => 12,
                'name' => 'راز و جرگلان',
                'en_name' => 'Raz and Jargalan',
                'latitude' => '37.9329427',
                'longitude' => '57.1008396',
            ],
            [
                'id' => 166,
                'province_id' => 12,
                'name' => 'شیروان',
                'en_name' => 'Shirvan',
                'latitude' => '37.4090473',
                'longitude' => '57.8974751',
            ],
            [
                'id' => 167,
                'province_id' => 12,
                'name' => 'فاروج',
                'en_name' => 'Farooj',
                'latitude' => '37.1874397',
                'longitude' => '57.5359291',
            ],
            [
                'id' => 168,
                'province_id' => 12,
                'name' => 'گرمه',
                'en_name' => 'Garmeh',
                'latitude' => '36.9881128',
                'longitude' => '56.2639641',
            ],
            [
                'id' => 169,
                'province_id' => 12,
                'name' => 'مانه و سملقان',
                'en_name' => 'Maneh Va Samalqan',
                'latitude' => '37.7550807',
                'longitude' => '56.077152',
            ],
            [
                'id' => 170,
                'province_id' => 13,
                'name' => 'آبادان',
                'en_name' => 'Abadan',
                'latitude' => '30.3277323',
                'longitude' => '48.2533108',
            ],
            [
                'id' => 171,
                'province_id' => 13,
                'name' => 'آغاجاری',
                'en_name' => 'Aghajari',
                'latitude' => '30.698551',
                'longitude' => '49.7949737',
            ],
            [
                'id' => 172,
                'province_id' => 13,
                'name' => 'امیدیه',
                'en_name' => 'Omidiyeh',
                'latitude' => '30.7577563',
                'longitude' => '49.6525591',
            ],
            [
                'id' => 173,
                'province_id' => 13,
                'name' => 'اندیکا',
                'en_name' => 'Andika',
                'latitude' => '32.2064064',
                'longitude' => '49.4348562',
            ],
            [
                'id' => 174,
                'province_id' => 13,
                'name' => 'اندیمشک',
                'en_name' => 'Andimeshk',
                'latitude' => '32.4618671',
                'longitude' => '48.3103301',
            ],
            [
                'id' => 175,
                'province_id' => 13,
                'name' => 'اهواز',
                'en_name' => 'Ahvaz',
                'latitude' => '31.3753623',
                'longitude' => '48.5305061',
            ],
            [
                'id' => 176,
                'province_id' => 13,
                'name' => 'ایذه',
                'en_name' => 'Izeh',
                'latitude' => '31.8251663',
                'longitude' => '49.8317521',
            ],
            [
                'id' => 177,
                'province_id' => 13,
                'name' => 'باغ ملک',
                'en_name' => 'Baghmalek',
                'latitude' => '31.5263096',
                'longitude' => '49.8638961',
            ],
            [
                'id' => 178,
                'province_id' => 13,
                'name' => 'باوی',
                'en_name' => 'Bavi',
                'latitude' => '31.470833',
                'longitude' => '48.860278',
            ],
            [
                'id' => 179,
                'province_id' => 13,
                'name' => 'بندر ماهشهر',
                'en_name' => 'Bandar Mahshahr',
                'latitude' => '30.5631054',
                'longitude' => '49.143594',
            ],
            [
                'id' => 180,
                'province_id' => 13,
                'name' => 'بهبهان',
                'en_name' => 'Behbahan',
                'latitude' => '30.5935469',
                'longitude' => '50.2071541',
            ],
            [
                'id' => 181,
                'province_id' => 13,
                'name' => 'حمیدیه',
                'en_name' => 'Hamidiyeh',
                'latitude' => '31.4747959',
                'longitude' => '48.4149454',
            ],
            [
                'id' => 182,
                'province_id' => 13,
                'name' => 'خرمشهر',
                'en_name' => 'Khorramshahr',
                'latitude' => '30.4115935',
                'longitude' => '48.1187413',
            ],
            [
                'id' => 183,
                'province_id' => 13,
                'name' => 'دزفول',
                'en_name' => 'Dezful',
                'latitude' => '32.4024737',
                'longitude' => '48.3177809',
            ],
            [
                'id' => 184,
                'province_id' => 13,
                'name' => 'دشت آزادگان',
                'en_name' => 'Dashte Azadeghan',
                'latitude' => '31.5950967',
                'longitude' => '47.4755307',
            ],
            [
                'id' => 185,
                'province_id' => 13,
                'name' => 'رامشیر',
                'en_name' => 'Ramshir',
                'latitude' => '30.8917634',
                'longitude' => '49.3916128',
            ],
            [
                'id' => 186,
                'province_id' => 13,
                'name' => 'رامهرمز',
                'en_name' => 'Ramhormoz',
                'latitude' => '31.2753145',
                'longitude' => '49.5737451',
            ],
            [
                'id' => 187,
                'province_id' => 13,
                'name' => 'شادگان',
                'en_name' => 'Shadegan',
                'latitude' => '30.6519393',
                'longitude' => '48.6369894',
            ],
            [
                'id' => 188,
                'province_id' => 13,
                'name' => 'شوش',
                'en_name' => 'Shush',
                'latitude' => '32.1953312',
                'longitude' => '48.2443998',
            ],
            [
                'id' => 189,
                'province_id' => 13,
                'name' => 'شوشتر',
                'en_name' => 'Shooshtar',
                'latitude' => '32.0410999',
                'longitude' => '48.7997669',
            ],
            [
                'id' => 190,
                'province_id' => 13,
                'name' => 'کارون',
                'en_name' => 'Karun',
                'latitude' => '31.3806844',
                'longitude' => '48.0090806',
            ],
            [
                'id' => 191,
                'province_id' => 13,
                'name' => 'گتوند',
                'en_name' => 'Gotvand',
                'latitude' => '32.2452778',
                'longitude' => '48.7651341',
            ],
            [
                'id' => 192,
                'province_id' => 13,
                'name' => 'لالی',
                'en_name' => 'Lali',
                'latitude' => '32.3293339',
                'longitude' => '49.0875577',
            ],
            [
                'id' => 193,
                'province_id' => 13,
                'name' => 'مسجد سلیمان',
                'en_name' => 'Masjed Soleyman',
                'latitude' => '31.9517205',
                'longitude' => '49.2194256',
            ],
            [
                'id' => 194,
                'province_id' => 13,
                'name' => 'هفتگل',
                'en_name' => 'Haftkel',
                'latitude' => '31.4549851',
                'longitude' => '49.5087288',
            ],
            [
                'id' => 195,
                'province_id' => 13,
                'name' => 'هندیجان',
                'en_name' => 'Hendijan',
                'latitude' => '30.2345225',
                'longitude' => '49.6924065',
            ],
            [
                'id' => 196,
                'province_id' => 13,
                'name' => 'هویزه',
                'en_name' => 'Hoveyzeh',
                'latitude' => '31.4655099',
                'longitude' => '48.0614304',
            ],
            [
                'id' => 197,
                'province_id' => 14,
                'name' => 'ابهر',
                'en_name' => 'Abhar',
                'latitude' => '36.1512257',
                'longitude' => '49.1992444',
            ],
            [
                'id' => 198,
                'province_id' => 14,
                'name' => 'ایجرود',
                'en_name' => 'Ijrud',
                'latitude' => '36.4235242',
                'longitude' => '48.247088',
            ],
            [
                'id' => 199,
                'province_id' => 14,
                'name' => 'خدابنده',
                'en_name' => 'Khodabandeh',
                'latitude' => '36.1223023',
                'longitude' => '48.557939',
            ],
            [
                'id' => 200,
                'province_id' => 14,
                'name' => 'خرمدره',
                'en_name' => 'Khorramdarreh',
                'latitude' => '36.2119644',
                'longitude' => '49.164676',
            ],
            [
                'id' => 201,
                'province_id' => 14,
                'name' => 'زنجان',
                'en_name' => 'Zanjan',
                'latitude' => '36.6811377',
                'longitude' => '48.4231828',
            ],
            [
                'id' => 202,
                'province_id' => 14,
                'name' => 'سلطانیه',
                'en_name' => 'Soltanieh',
                'latitude' => '36.4348691',
                'longitude' => '48.7841463',
            ],
            [
                'id' => 203,
                'province_id' => 14,
                'name' => 'طارم',
                'en_name' => 'Tarom',
                'latitude' => '37.0237912',
                'longitude' => '48.7728549',
            ],
            [
                'id' => 204,
                'province_id' => 14,
                'name' => 'ماهنشان',
                'en_name' => 'Mahneshan',
                'latitude' => '36.7426321',
                'longitude' => '47.6629185',
            ],
            [
                'id' => 205,
                'province_id' => 15,
                'name' => 'آرادان',
                'en_name' => 'Aradan',
                'latitude' => '35.2481574',
                'longitude' => '52.4820268',
            ],
            [
                'id' => 206,
                'province_id' => 15,
                'name' => 'دامغان',
                'en_name' => 'Damghan',
                'latitude' => '36.1645183',
                'longitude' => '54.3245171',
            ],
            [
                'id' => 207,
                'province_id' => 15,
                'name' => 'سرخه',
                'en_name' => 'Sorkheh',
                'latitude' => '35.4680219',
                'longitude' => '53.2010563',
            ],
            [
                'id' => 208,
                'province_id' => 15,
                'name' => 'سمنان',
                'en_name' => 'Semnan',
                'latitude' => '35.5777395',
                'longitude' => '53.3490937',
            ],
            [
                'id' => 209,
                'province_id' => 15,
                'name' => 'شاهرود',
                'en_name' => 'Shahroud',
                'latitude' => '36.4057075',
                'longitude' => '54.938848',
            ],
            [
                'id' => 210,
                'province_id' => 15,
                'name' => 'گرمسار',
                'en_name' => 'Garmsār',
                'latitude' => '35.2028784',
                'longitude' => '52.3048556',
            ],
            [
                'id' => 211,
                'province_id' => 15,
                'name' => 'مهدی شهر',
                'en_name' => 'Mahdi Shahr',
                'latitude' => '35.7073452',
                'longitude' => '53.2507942',
            ],
            [
                'id' => 212,
                'province_id' => 15,
                'name' => 'میامی',
                'en_name' => 'Mayamey',
                'latitude' => '36.4120092',
                'longitude' => '55.6413316',
            ],
            [
                'id' => 213,
                'province_id' => 16,
                'name' => 'ایرانشهر',
                'en_name' => 'Iranshahr',
                'latitude' => '27.2170347',
                'longitude' => '60.6377929',
            ],
            [
                'id' => 214,
                'province_id' => 16,
                'name' => 'چابهار',
                'en_name' => 'Chabahar',
                'latitude' => '25.310909',
                'longitude' => '60.6101768',
            ],
            [
                'id' => 215,
                'province_id' => 16,
                'name' => 'خاش',
                'en_name' => 'Khash',
                'latitude' => '28.2228012',
                'longitude' => '61.1548491',
            ],
            [
                'id' => 216,
                'province_id' => 16,
                'name' => 'دلگان',
                'en_name' => 'Delgan',
                'latitude' => '27.5175535',
                'longitude' => '59.056143',
            ],
            [
                'id' => 217,
                'province_id' => 16,
                'name' => 'زابل',
                'en_name' => 'Zabol',
                'latitude' => '31.0402692',
                'longitude' => '61.428313',
            ],
            [
                'id' => 218,
                'province_id' => 16,
                'name' => 'زاهدان',
                'en_name' => 'Zahedan',
                'latitude' => '29.4832308',
                'longitude' => '60.8049714',
            ],
            [
                'id' => 219,
                'province_id' => 16,
                'name' => 'زهک',
                'en_name' => 'Zahak',
                'latitude' => '30.8913954',
                'longitude' => '61.6654442',
            ],
            [
                'id' => 220,
                'province_id' => 16,
                'name' => 'سراوان',
                'en_name' => 'Saravan',
                'latitude' => '27.3506847',
                'longitude' => '62.2838155',
            ],
            [
                'id' => 221,
                'province_id' => 16,
                'name' => 'سرباز',
                'en_name' => 'Sarbaz',
                'latitude' => '26.6323637',
                'longitude' => '61.2495518',
            ],
            [
                'id' => 222,
                'province_id' => 16,
                'name' => 'سیب و سوران',
                'en_name' => 'Sib va Sooran',
                'latitude' => '27.3663678',
                'longitude' => '61.3141766',
            ],
            [
                'id' => 223,
                'province_id' => 16,
                'name' => 'فنوج',
                'en_name' => 'Fanouj',
                'latitude' => '26.5734036',
                'longitude' => '59.6299265',
            ],
            [
                'id' => 224,
                'province_id' => 16,
                'name' => 'قصرقند',
                'en_name' => 'Qasr-e-qand',
                'latitude' => '26.2271908',
                'longitude' => '60.7146113',
            ],
            [
                'id' => 225,
                'province_id' => 16,
                'name' => 'کنارک',
                'en_name' => 'Konarak',
                'latitude' => '25.4001432',
                'longitude' => '60.3150244',
            ],
            [
                'id' => 226,
                'province_id' => 16,
                'name' => 'مهرستان',
                'en_name' => 'Mehrestan',
                'latitude' => '27.133928',
                'longitude' => '61.6546295',
            ],
            [
                'id' => 227,
                'province_id' => 16,
                'name' => 'میرجاوه',
                'en_name' => 'Mirjaveh',
                'latitude' => '29.0181035',
                'longitude' => '61.4321623',
            ],
            [
                'id' => 228,
                'province_id' => 16,
                'name' => 'نیک شهر',
                'en_name' => 'Nikshahr',
                'latitude' => '26.2321716',
                'longitude' => '60.2177486',
            ],
            [
                'id' => 229,
                'province_id' => 16,
                'name' => 'نیمروز',
                'en_name' => 'Nimrooz',
                'latitude' => '31.1150077',
                'longitude' => '61.3925885',
            ],
            [
                'id' => 230,
                'province_id' => 16,
                'name' => 'هامون',
                'en_name' => 'Hamoon',
                'latitude' => '25.2862712',
                'longitude' => '60.6404113',
            ],
            [
                'id' => 231,
                'province_id' => 16,
                'name' => 'هیرمند',
                'en_name' => 'Hirmand',
                'latitude' => '31.0402042',
                'longitude' => '61.4979214',
            ],
            [
                'id' => 232,
                'province_id' => 17,
                'name' => 'آباده',
                'en_name' => 'Abadeh',
                'latitude' => '31.1612476',
                'longitude' => '52.6127951',
            ],
            [
                'id' => 233,
                'province_id' => 17,
                'name' => 'ارسنجان',
                'en_name' => 'Arsenjan',
                'latitude' => '29.9189654',
                'longitude' => '53.2829187',
            ],
            [
                'id' => 234,
                'province_id' => 17,
                'name' => 'استهبان',
                'en_name' => 'Estahban',
                'latitude' => '29.1283534',
                'longitude' => '54.00042',
            ],
            [
                'id' => 235,
                'province_id' => 17,
                'name' => 'اقلید',
                'en_name' => 'Eqlid',
                'latitude' => '30.901473',
                'longitude' => '52.6527923',
            ],
            [
                'id' => 236,
                'province_id' => 17,
                'name' => 'بوانات',
                'en_name' => 'Bavanat',
                'latitude' => '30.4864762',
                'longitude' => '53.5872101',
            ],
            [
                'id' => 237,
                'province_id' => 17,
                'name' => 'پاسارگاد',
                'en_name' => 'Pasargad',
                'latitude' => '30.191394',
                'longitude' => '53.1720793',
            ],
            [
                'id' => 238,
                'province_id' => 17,
                'name' => 'جهرم',
                'en_name' => 'Jahrom',
                'latitude' => '28.5307334',
                'longitude' => '53.5185216',
            ],
            [
                'id' => 239,
                'province_id' => 17,
                'name' => 'خرامه',
                'en_name' => 'Kharameh',
                'latitude' => '29.5004044',
                'longitude' => '53.3010721',
            ],
            [
                'id' => 240,
                'province_id' => 17,
                'name' => 'خرم بید',
                'en_name' => 'Khorrambid',
                'latitude' => '30.5004486',
                'longitude' => '53.0808013',
            ],
            [
                'id' => 241,
                'province_id' => 17,
                'name' => 'خنج',
                'en_name' => 'Khonj',
                'latitude' => '27.887675',
                'longitude' => '53.4115789',
            ],
            [
                'id' => 242,
                'province_id' => 17,
                'name' => 'داراب',
                'en_name' => 'Darab',
                'latitude' => '28.7516993',
                'longitude' => '54.5091814',
            ],
            [
                'id' => 243,
                'province_id' => 17,
                'name' => 'رستم',
                'en_name' => 'Rostam',
                'latitude' => '30.233333',
                'longitude' => '51.516667',
            ],
            [
                'id' => 244,
                'province_id' => 17,
                'name' => 'زرین دشت',
                'en_name' => 'Zarrin Dasht',
                'latitude' => '28.3599822',
                'longitude' => '54.4029235',
            ],
            [
                'id' => 245,
                'province_id' => 17,
                'name' => 'سپیدان',
                'en_name' => 'Sepidan',
                'latitude' => '30.2039268',
                'longitude' => '51.8967963',
            ],
            [
                'id' => 246,
                'province_id' => 17,
                'name' => 'سروستان',
                'en_name' => 'Sarvestan',
                'latitude' => '29.2702627',
                'longitude' => '53.2073019',
            ],
            [
                'id' => 247,
                'province_id' => 17,
                'name' => 'شیراز',
                'en_name' => 'Shiraz',
                'latitude' => '29.6657999',
                'longitude' => '52.3929298',
            ],
            [
                'id' => 248,
                'province_id' => 17,
                'name' => 'فراشبند',
                'en_name' => 'Farashband',
                'latitude' => '28.8506041',
                'longitude' => '52.0610326',
            ],
            [
                'id' => 249,
                'province_id' => 17,
                'name' => 'فسا',
                'en_name' => 'Fasa',
                'latitude' => '28.9488106',
                'longitude' => '53.5992043',
            ],
            [
                'id' => 250,
                'province_id' => 17,
                'name' => 'فیروزآباد',
                'en_name' => 'Firuzabad',
                'latitude' => '28.84489',
                'longitude' => '52.5284503',
            ],
            [
                'id' => 251,
                'province_id' => 17,
                'name' => 'قیروکارزین',
                'en_name' => 'Ghirokarzin',
                'latitude' => '28.3929149',
                'longitude' => '52.7315849',
            ],
            [
                'id' => 252,
                'province_id' => 17,
                'name' => 'کازرون',
                'en_name' => 'Kazerun',
                'latitude' => '29.6259101',
                'longitude' => '51.6121382',
            ],
            [
                'id' => 253,
                'province_id' => 17,
                'name' => 'کوار',
                'en_name' => 'Kavar',
                'latitude' => '29.2118966',
                'longitude' => '52.6502602',
            ],
            [
                'id' => 254,
                'province_id' => 17,
                'name' => 'گراش',
                'en_name' => 'Gerash',
                'latitude' => '27.6751327',
                'longitude' => '54.075863',
            ],
            [
                'id' => 255,
                'province_id' => 17,
                'name' => 'لارستان',
                'en_name' => 'Larestan',
                'latitude' => '27.6688823',
                'longitude' => '54.246845',
            ],
            [
                'id' => 256,
                'province_id' => 17,
                'name' => 'لامرد',
                'en_name' => 'Lamerd',
                'latitude' => '27.3414567',
                'longitude' => '53.1543223',
            ],
            [
                'id' => 257,
                'province_id' => 17,
                'name' => 'مرودشت',
                'en_name' => 'Marvdasht',
                'latitude' => '29.8903524',
                'longitude' => '52.7829545',
            ],
            [
                'id' => 258,
                'province_id' => 17,
                'name' => 'ممسنی',
                'en_name' => 'Mamasani',
                'latitude' => '30.1135673',
                'longitude' => '51.503691',
            ],
            [
                'id' => 259,
                'province_id' => 17,
                'name' => 'مهر',
                'en_name' => 'Mohr',
                'latitude' => '27.5516735',
                'longitude' => '52.8721762',
            ],
            [
                'id' => 260,
                'province_id' => 17,
                'name' => 'نی ریز',
                'en_name' => 'Neyriz',
                'latitude' => '29.1904855',
                'longitude' => '54.2861502',
            ],
            [
                'id' => 261,
                'province_id' => 18,
                'name' => 'آبیک',
                'en_name' => 'Abyek',
                'latitude' => '36.0471512',
                'longitude' => '50.5181835',
            ],
            [
                'id' => 262,
                'province_id' => 18,
                'name' => 'آوج',
                'en_name' => 'Avaj',
                'latitude' => '35.5777358',
                'longitude' => '49.2120016',
            ],
            [
                'id' => 263,
                'province_id' => 18,
                'name' => 'البرز',
                'en_name' => 'Alborz',
                'latitude' => '36.0235385',
                'longitude' => '50.5568554',
            ],
            [
                'id' => 264,
                'province_id' => 18,
                'name' => 'بویین زهرا',
                'en_name' => 'Buin Zahra',
                'latitude' => '35.7655339',
                'longitude' => '50.0423167',
            ],
            [
                'id' => 265,
                'province_id' => 18,
                'name' => 'تاکستان',
                'en_name' => 'Takestan',
                'latitude' => '36.0708383',
                'longitude' => '49.6609063',
            ],
            [
                'id' => 266,
                'province_id' => 18,
                'name' => 'قزوین',
                'en_name' => 'Qazvin',
                'latitude' => '36.2813381',
                'longitude' => '49.9466454',
            ],
            [
                'id' => 267,
                'province_id' => 19,
                'name' => 'قم',
                'en_name' => 'Qom',
                'latitude' => '34.6887845',
                'longitude' => '50.7119792',
            ],
            [
                'id' => 398,
                'province_id' => 29,
                'name' => 'ابوموسی',
                'en_name' => 'Abumusa',
                'latitude' => '25.8779875',
                'longitude' => '55.0152127',
            ],
            [
                'id' => 399,
                'province_id' => 29,
                'name' => 'بستک',
                'en_name' => 'Bastak',
                'latitude' => '27.1963552',
                'longitude' => '54.3425415',
            ],
            [
                'id' => 400,
                'province_id' => 29,
                'name' => 'بشاگرد',
                'en_name' => 'Bashagard',
                'latitude' => '26.4587574',
                'longitude' => '57.884259',
            ],
            [
                'id' => 401,
                'province_id' => 29,
                'name' => 'بندر عباس',
                'en_name' => 'Bandar Abbas',
                'latitude' => '27.1901697',
                'longitude' => '56.0978121',
            ],
            [
                'id' => 402,
                'province_id' => 29,
                'name' => 'بندرلنگه',
                'en_name' => 'Bandar Lengeh',
                'latitude' => '26.564103',
                'longitude' => '54.8733293',
            ],
            [
                'id' => 403,
                'province_id' => 29,
                'name' => 'پارسیان',
                'en_name' => 'Parsian',
                'latitude' => '27.2167557',
                'longitude' => '53.0218647',
            ],
            [
                'id' => 404,
                'province_id' => 29,
                'name' => 'جاسک',
                'en_name' => 'Jask',
                'latitude' => '25.6538901',
                'longitude' => '57.769956',
            ],
            [
                'id' => 405,
                'province_id' => 29,
                'name' => 'حاجی اباد',
                'en_name' => 'Haji Abad',
                'latitude' => '28.313518',
                'longitude' => '55.8786956',
            ],
            [
                'id' => 406,
                'province_id' => 29,
                'name' => 'خمیر',
                'en_name' => 'Khamir',
                'latitude' => '26.9518909',
                'longitude' => '55.5726884',
            ],
            [
                'id' => 407,
                'province_id' => 30,
                'name' => 'رودان',
                'en_name' => 'Roodān',
                'latitude' => '27.5572968',
                'longitude' => '56.9776321',
            ],
            [
                'id' => 408,
                'province_id' => 29,
                'name' => 'سیریک',
                'en_name' => 'Sirik',
                'latitude' => '26.5273545',
                'longitude' => '57.0900247',
            ],
            [
                'id' => 409,
                'province_id' => 29,
                'name' => 'قشم',
                'en_name' => 'Qeshm',
                'latitude' => '26.9582535',
                'longitude' => '56.1888022',
            ],
            [
                'id' => 410,
                'province_id' => 29,
                'name' => 'میناب',
                'en_name' => 'Minab',
                'latitude' => '27.1384793',
                'longitude' => '57.0105861',
            ],
            [
                'id' => 411,
                'province_id' => 30,
                'name' => 'اسدآباد',
                'en_name' => 'Asadabad',
                'latitude' => '34.7812368',
                'longitude' => '48.1020925',
            ],
            [
                'id' => 412,
                'province_id' => 30,
                'name' => 'بهار',
                'en_name' => 'Bahar',
                'latitude' => '34.893957',
                'longitude' => '48.4032291',
            ],
            [
                'id' => 413,
                'province_id' => 30,
                'name' => 'تویسرکان',
                'en_name' => 'Tuyserkan',
                'latitude' => '34.5481925',
                'longitude' => '48.4323851',
            ],
            [
                'id' => 414,
                'province_id' => 30,
                'name' => 'رزن',
                'en_name' => 'Razan',
                'latitude' => '35.3879465',
                'longitude' => '49.0176485',
            ],
            [
                'id' => 415,
                'province_id' => 30,
                'name' => 'فامنین',
                'en_name' => 'Famenin',
                'latitude' => '35.1130435',
                'longitude' => '48.9569448',
            ],
            [
                'id' => 416,
                'province_id' => 30,
                'name' => 'کبودرآهنگ',
                'en_name' => 'Kabudrahang',
                'latitude' => '35.2094297',
                'longitude' => '48.7067913',
            ],
            [
                'id' => 417,
                'province_id' => 30,
                'name' => 'ملایر',
                'en_name' => 'Malayer',
                'latitude' => '34.301496',
                'longitude' => '48.7882226',
            ],
            [
                'id' => 418,
                'province_id' => 30,
                'name' => 'نهاوند',
                'en_name' => 'Nahavand',
                'latitude' => '34.1948978',
                'longitude' => '48.3392422',
            ],
            [
                'id' => 419,
                'province_id' => 30,
                'name' => 'همدان',
                'en_name' => 'Hamedan',
                'latitude' => '34.8124497',
                'longitude' => '48.4400271',
            ],
            [
                'id' => 420,
                'province_id' => 31,
                'name' => 'ابرکوه',
                'en_name' => 'Abarkooh',
                'latitude' => '31.1263544',
                'longitude' => '53.2215924',
            ],
            [
                'id' => 421,
                'province_id' => 31,
                'name' => 'اردکان',
                'en_name' => 'Ardakan',
                'latitude' => '32.3104532',
                'longitude' => '53.9989613',
            ],
            [
                'id' => 422,
                'province_id' => 31,
                'name' => 'اشکذر',
                'en_name' => 'Ashkezar',
                'latitude' => '32.0007766',
                'longitude' => '54.1923592',
            ],
            [
                'id' => 423,
                'province_id' => 31,
                'name' => 'بافق',
                'en_name' => 'Bafgh',
                'latitude' => '31.6125914',
                'longitude' => '55.3802341',
            ],
            [
                'id' => 424,
                'province_id' => 31,
                'name' => 'بهاباد',
                'en_name' => 'Bahabad',
                'latitude' => '31.8702652',
                'longitude' => '56.0046098',
            ],
            [
                'id' => 425,
                'province_id' => 31,
                'name' => 'تفت',
                'en_name' => 'Taft',
                'latitude' => '31.7575311',
                'longitude' => '54.1720695',
            ],
            [
                'id' => 426,
                'province_id' => 31,
                'name' => 'خاتم',
                'en_name' => 'Khatam',
                'latitude' => '31.8729614',
                'longitude' => '54.3914155',
            ],
            [
                'id' => 427,
                'province_id' => 31,
                'name' => 'مهریز',
                'en_name' => 'Mehriz',
                'latitude' => '31.5798485',
                'longitude' => '54.4066942',
            ],
            [
                'id' => 428,
                'province_id' => 31,
                'name' => 'میبد',
                'en_name' => 'Meybod',
                'latitude' => '32.2085722',
                'longitude' => '53.9747118',
            ],
            [
                'id' => 429,
                'province_id' => 31,
                'name' => 'یزد',
                'en_name' => 'Yazd',
                'latitude' => '31.879685',
                'longitude' => '54.2667269',
            ],
	        [
		        'id' => 268,
		        'province_id' => 20,
		        'name' => 'بانه',
		        'en_name' => 'Baneh',
		        'latitude' => '35.9945143',
		        'longitude' => '45.8703015',
	        ],
	        [
		        'id' => 269,
		        'province_id' => 20,
		        'name' => 'بیجار',
		        'en_name' => 'Bijar',
		        'latitude' => '35.8727737',
		        'longitude' => ',47.5806282',
	        ],
	        [
		        'id' => 270,
		        'province_id' => 20,
		        'name' => 'دهگلان',
		        'en_name' => 'Dehgolan',
		        'latitude' => '35.2798004',
		        'longitude' => '47.4111664',
	        ],
	        [
		        'id' => 271,
		        'province_id' => 20,
		        'name' => 'دیواندره',
		        'en_name' => 'Divandarreh',
		        'latitude' => '35.9159013',
		        'longitude' => '47.0080946',
	        ],
	        [
		        'id' => 272,
		        'province_id' => 20,
		        'name' => 'سروآباد',
		        'en_name' => 'Sarvabad',
		        'latitude' => '35.3095563',
		        'longitude' => '46.3575411',
	        ],
	        [
		        'id' => 273,
		        'province_id' => 20,
		        'name' => 'سقز',
		        'en_name' => 'Saqqez',
		        'latitude' => '36.2411826',
		        'longitude' => '46.2429565',
	        ],
	        [
		        'id' => 274,
		        'province_id' => 20,
		        'name' => 'سنندج',
		        'en_name' => 'Sanandaj',
		        'latitude' => '35.2899686',
		        'longitude' => '46.939342',
	        ],
	        [
		        'id' => 275,
		        'province_id' => 20,
		        'name' => 'قروه',
		        'en_name' => 'Qorveh',
		        'latitude' => '35.1658754',
		        'longitude' => '47.7900766',
	        ],
	        [
		        'id' => 276,
		        'province_id' => 20,
		        'name' => 'کامیاران',
		        'en_name' => 'Kamyaran',
		        'latitude' => '34.7966655',
		        'longitude' => '46.9229077',
	        ],
	        [
		        'id' => 277,
		        'province_id' => 20,
		        'name' => 'مریوان',
		        'en_name' => 'Marivan',
		        'latitude' => '35.5168281',
		        'longitude' => '46.1609028',
	        ],
	        [
		        'id' => 301,
		        'province_id' => 22,
		        'name' => 'اسلام آبادغرب',
		        'en_name' => 'Eslamabad-e-Gharb',
		        'latitude' => '34.1100924',
		        'longitude' => '46.4957279',
	        ],
	        [
		        'id' => 302,
		        'province_id' => 22,
		        'name' => 'پاوه',
		        'en_name' => 'Paveh',
		        'latitude' => '35.0454192',
		        'longitude' => '46.343765',
	        ],
	        [
		        'id' => 303,
		        'province_id' => 22,
		        'name' => 'ثلاث باباجانی',
		        'en_name' => 'Salas Babajani',
		        'latitude' => '34.7355811',
		        'longitude' => '46.1433935',
	        ],
	        [
		        'id' => 304,
		        'province_id' => 22,
		        'name' => 'جوانرود',
		        'en_name' => 'Javanrud',
		        'latitude' => '34.8056264',
		        'longitude' => '46.4782188',
	        ],
	        [
		        'id' => 305,
		        'province_id' => 22,
		        'name' => 'دالاهو',
		        'en_name' => 'Kerend-e Gharb',
		        'latitude' => '34.278016',
		        'longitude' => '46.2267029',
	        ],
	        [
		        'id' => 306,
		        'province_id' => 22,
		        'name' => 'روانسر',
		        'en_name' => 'Ravansar',
		        'latitude' => '34.7090539',
		        'longitude' => '46.6403688',
	        ],
	        [
		        'id' => 307,
		        'province_id' => 22,
		        'name' => 'سرپل ذهاب',
		        'en_name' => 'Sarpol Zahab',
		        'latitude' => '34.4592223',
		        'longitude' => '45.8457755',
	        ],
	        [
		        'id' => 308,
		        'province_id' => 22,
		        'name' => 'سنقر',
		        'en_name' => 'Sonqor',
		        'latitude' => '34.7744618',
		        'longitude' => '47.5662512',
	        ],
	        [
		        'id' => 309,
		        'province_id' => 22,
		        'name' => 'صحنه',
		        'en_name' => 'Sahneh',
		        'latitude' => '34.4793187',
		        'longitude' => '47.6680361',
	        ],
	        [
		        'id' => 310,
		        'province_id' => 22,
		        'name' => 'قصرشیرین',
		        'en_name' => 'Qasr-e Shirin',
		        'latitude' => '34.5167207',
		        'longitude' => '45.5709027',
	        ],
	        [
		        'id' => 311,
		        'province_id' => 22,
		        'name' => 'کرمانشاه',
		        'en_name' => 'Kermanshah',
		        'latitude' => '34.3372497',
		        'longitude' => '47.0258332',
	        ],
	        [
		        'id' => 312,
		        'province_id' => 22,
		        'name' => 'کنگاور',
		        'en_name' => 'Kangavar',
		        'latitude' => '34.5017084',
		        'longitude' => '47.9441426',
	        ],
	        [
		        'id' => 313,
		        'province_id' => 22,
		        'name' => 'گیلانغرب',
		        'en_name' => 'Gilan Gharb',
		        'latitude' => '34.1398952',
		        'longitude' => '45.9149337',
	        ],
	        [
		        'id' => 314,
		        'province_id' => 22,
		        'name' => 'هرسین',
		        'en_name' => 'Harsin',
		        'latitude' => '34.2708338',
		        'longitude' => '47.5695426',
	        ],
	        [
		        'id' => 278,
		        'province_id' => 21,
		        'name' => 'ارزوییه',
		        'en_name' => 'Orzueeyeh',
		        'latitude' => '28.4583908',
		        'longitude' => '56.3532177',
	        ],
	        [
		        'id' => 279,
		        'province_id' => 21,
		        'name' => 'انار',
		        'en_name' => 'Anar',
		        'latitude' => '30.8656849',
		        'longitude' => '55.2572822',
	        ],
	        [
		        'id' => 280,
		        'province_id' => 21,
		        'name' => 'بافت',
		        'en_name' => 'Baft',
		        'latitude' => '29.2308726',
		        'longitude' => '56.5792054',
	        ],
	        [
		        'id' => 281,
		        'province_id' => 21,
		        'name' => 'بردسیر',
		        'en_name' => 'Bardsir',
		        'latitude' => '29.9259938',
		        'longitude' => '56.5349144',
	        ],
	        [
		        'id' => 282,
		        'province_id' => 21,
		        'name' => 'بم',
		        'en_name' => 'Bam',
		        'latitude' => '29.1023289',
		        'longitude' => '58.3113521',
	        ],
	        [
		        'id' => 283,
		        'province_id' => 21,
		        'name' => 'جیرفت',
		        'en_name' => 'Jiroft',
		        'latitude' => '28.6919493',
		        'longitude' => '57.6469134',
	        ],
	        [
		        'id' => 284,
		        'province_id' => 21,
		        'name' => 'رابر',
		        'en_name' => 'Rābor',
		        'latitude' => '29.2908138',
		        'longitude' => '56.899781',
	        ],
	        [
		        'id' => 285,
		        'province_id' => 21,
		        'name' => 'راور',
		        'en_name' => 'Ravar',
		        'latitude' => '31.2692164',
		        'longitude' => '56.7697042',
	        ],
	        [
		        'id' => 286,
		        'province_id' => 21,
		        'name' => 'رفسنجان',
		        'en_name' => 'Rafsanjan',
		        'latitude' => '30.3671961',
		        'longitude' => '55.9213258',
	        ],
	        [
		        'id' => 287,
		        'province_id' => 21,
		        'name' => 'رودبارجنوب',
		        'en_name' => 'Roudbar',
		        'latitude' => '28.0299375',
		        'longitude' => '57.9742525',
	        ],
	        [
		        'id' => 288,
		        'province_id' => 21,
		        'name' => 'ریگان',
		        'en_name' => 'Mohammadābād-e-Rigan',
		        'latitude' => '28.6469444',
		        'longitude' => '59.0014313',
	        ],
	        [
		        'id' => 289,
		        'province_id' => 21,
		        'name' => 'زرند',
		        'en_name' => 'Zarand',
		        'latitude' => '30.8135763',
		        'longitude' => '56.5456002',
	        ],
	        [
		        'id' => 290,
		        'province_id' => 21,
		        'name' => 'سیرجان',
		        'en_name' => 'Sirjan',
		        'latitude' => '29.4854265',
		        'longitude' => '55.5933768',
	        ],
	        [
		        'id' => 291,
		        'province_id' => 21,
		        'name' => 'شهربابک',
		        'en_name' => 'Shahrbabak',
		        'latitude' => '30.1197677',
		        'longitude' => '55.0923151',
	        ],
	        [
		        'id' => 292,
		        'province_id' => 21,
		        'name' => 'عنبرآباد',
		        'en_name' => 'Anbarabad',
		        'latitude' => '28.4778558',
		        'longitude' => '57.8243492',
	        ],
	        [
		        'id' => 293,
		        'province_id' => 21,
		        'name' => 'فاریاب',
		        'en_name' => 'Faryab',
		        'latitude' => '28.0909555',
		        'longitude' => '57.2091577',
	        ],
	        [
		        'id' => 294,
		        'province_id' => 21,
		        'name' => 'فهرج',
		        'en_name' => 'Fahraj',
		        'latitude' => '28.9458556',
		        'longitude' => '58.8759898',
	        ],
	        [
		        'id' => 295,
		        'province_id' => 21,
		        'name' => 'قلعه گنج',
		        'en_name' => 'Ghalehganj',
		        'latitude' => '27.5244069',
		        'longitude' => '57.8530168',
	        ],
	        [
		        'id' => 296,
		        'province_id' => 21,
		        'name' => 'کرمان',
		        'en_name' => 'Kerman',
		        'latitude' => '30.2730323',
		        'longitude' => '56.9962096',
	        ],
	        [
		        'id' => 297,
		        'province_id' => 21,
		        'name' => 'کوهبنان',
		        'en_name' => 'Kouhbanan',
		        'latitude' => '31.4126292',
		        'longitude' => '56.2713052',
	        ],
	        [
		        'id' => 298,
		        'province_id' => 21,
		        'name' => 'کهنوج',
		        'en_name' => 'Kahnooj',
		        'latitude' => '27.9793488',
		        'longitude' => '57.6659248',
	        ],
	        [
		        'id' => 299,
		        'province_id' => 21,
		        'name' => 'منوجان',
		        'en_name' => 'Manoojan',
		        'latitude' => '27.3682492',
		        'longitude' => '57.2028964',
	        ],
	        [
		        'id' => 300,
		        'province_id' => 21,
		        'name' => 'نرماشیر',
		        'en_name' => 'Narmashir',
		        'latitude' => '28.9531038',
		        'longitude' => '58.6899197',
	        ],
	        [
		        'id' => 364,
		        'province_id' => 27,
		        'name' => 'آمل',
		        'en_name' => 'Amol',
		        'latitude' => '36.4660084',
		        'longitude' => '52.323503',
	        ],
	        [
		        'id' => 365,
		        'province_id' => 27,
		        'name' => 'بابل',
		        'en_name' => 'Babol',
		        'latitude' => '36.538381',
		        'longitude' => '52.6415535',
	        ],
	        [
		        'id' => 366,
		        'province_id' => 27,
		        'name' => 'بابلسر',
		        'en_name' => 'Babolsar',
		        'latitude' => '36.6977363',
		        'longitude' => '52.6279693',
	        ],
	        [
		        'id' => 367,
		        'province_id' => 27,
		        'name' => 'بهشهر',
		        'en_name' => 'Behshahr',
		        'latitude' => '36.6910235',
		        'longitude' => '53.4998124',
	        ],
	        [
		        'id' => 368,
		        'province_id' => 27,
		        'name' => 'تنکابن',
		        'en_name' => 'Tonekabon',
		        'latitude' => '36.8160236',
		        'longitude' => '50.8420867',
	        ],	        [
		        'id' => 369,
		        'province_id' => 27,
		        'name' => 'جویبار',
		        'en_name' => 'Juybar',
		        'latitude' => '36.6427655',
		        'longitude' => '52.8831624',
	        ],
	        [
		        'id' => 370,
		        'province_id' => 27,
		        'name' => 'چالوس',
		        'en_name' => 'Chalus',
		        'latitude' => '36.6560932',
		        'longitude' => '51.3875836',
	        ],
	        [
		        'id' => 371,
		        'province_id' => 27,
		        'name' => 'رامسر',
		        'en_name' => 'Ramsar',
		        'latitude' => '36.929072',
		        'longitude' => '50.6019754',
	        ],
	        [
		        'id' => 372,
		        'province_id' => 27,
		        'name' => 'ساری',
		        'en_name' => 'Sari',
		        'latitude' => '36.5559137',
		        'longitude' => '53.0374294',
	        ],
	        [
		        'id' => 373,
		        'province_id' => 27,
		        'name' => 'سوادکوه',
		        'en_name' => 'ُSavadkoh',
		        'latitude' => '35.977647',
		        'longitude' => '52.682463',
	        ],
	        [
		        'id' => 374,
		        'province_id' => 27,
		        'name' => 'سوادکوه شمالی',
		        'en_name' => 'North Savadkuh',
		        'latitude' => '36.366667',
		        'longitude' => '52.866667',
	        ],
	        [
		        'id' => 375,
		        'province_id' => 27,
		        'name' => 'سیمرغ',
		        'en_name' => 'Kia Kola',
		        'latitude' => '36.5833441',
		        'longitude' => '52.7989625',
	        ],
	        [
		        'id' => 376,
		        'province_id' => 27,
		        'name' => 'عباس آباد',
		        'en_name' => 'Abbasabad',
		        'latitude' => '36.7245438',
		        'longitude' => '51.0791296',
	        ],
	        [
		        'id' => 377,
		        'province_id' => 27,
		        'name' => 'فریدونکنار',
		        'en_name' => 'Fereydunkenar',
		        'latitude' => '36.6862445',
		        'longitude' => '52.5073526',
	        ],
	        [
		        'id' => 378,
		        'province_id' => 27,
		        'name' => 'قایم شهر',
		        'en_name' => 'Fereydunkenar',
		        'latitude' => '36.6862445',
		        'longitude' => '52.5073526',
	        ],
	        [
		        'id' => 379,
		        'province_id' => 27,
		        'name' => 'کلاردشت',
		        'en_name' => 'Kelardasht',
		        'latitude' => '36.4930711',
		        'longitude' => '51.1189765',
	        ],
	        [
		        'id' => 380,
		        'province_id' => 27,
		        'name' => 'گلوگاه',
		        'en_name' => 'Galugah',
		        'latitude' => '36.7279187',
		        'longitude' => '53.8021926',
	        ],
	        [
		        'id' => 381,
		        'province_id' => 27,
		        'name' => 'محمودآباد',
		        'en_name' => 'Mahmudabad',
		        'latitude' => '36.6280668',
		        'longitude' => '52.2399606',
	        ],
	        [
		        'id' => 382,
		        'province_id' => 27,
		        'name' => 'میاندورود',
		        'en_name' => 'Miandorud',
		        'latitude' => '36.5943467',
		        'longitude' => '53.2132777',
	        ],
	        [
		        'id' => 383,
		        'province_id' => 27,
		        'name' => 'نکا',
		        'en_name' => 'Neka',
		        'latitude' => '36.6477583',
		        'longitude' => '53.2705591',
	        ],
	        [
		        'id' => 384,
		        'province_id' => 27,
		        'name' => 'نور',
		        'en_name' => 'Nur',
		        'latitude' => '36.5742131',
		        'longitude' => '52.0117126',
	        ],
	        [
		        'id' => 385,
		        'province_id' => 27,
		        'name' => 'نوشهر',
		        'en_name' => 'Nowshahr',
		        'latitude' => '36.6502418',
		        'longitude' => '51.4693374,',
	        ],
        ]);
    }
}
